/*
 * src/game/invitems.c -- weapon static records: RETIRED at S484 F13 (2026-04-30).
 *
 * What used to live here (5789 lines, 86 weapons + supporting records):
 *   - g_Weapons[]                                    array of struct weapon *
 *   - 75+ invitem_*  static struct weapon            records (some shared
 *                                                   across multiple slots)
 *   - 150+ invfunc_* static struct weaponfunc_*      records (8 variants)
 *   - 80+  invammo_* static struct inventory_ammo    records
 *   - 13   invaimsettings_* + the default
 *   - 8    invnoisesettings_* + the silent default
 *   - 4    invrecoilsettings_* + the default
 *   - 110  invanim_*[]    struct guncmd[]            opcode-array animations
 *   - 14   gunviscmds_*[] struct gunviscmd[]         visibility command lists
 *   - 14   invpartvisibility_*[] modelpartvisibility[] tables
 *   - 2    vibrationstart/max_reaper f32[12]         arrays
 *
 * All of the above is now sourced from base/weapons.pdbase (12.8k-line JSON
 * archive authored at S591 F11, generated by devtools/extract_weapons_pdbase.py).
 * The runtime loader (port/src/loader_pdbase.c, S591 F12) parses the JSON
 * at startup and populates the catalog manager's typed pools. The manager
 * (port/src/catalog_mgr_weapons.c) is the sole accessor surface for all
 * weapon DATA reads -- struct weapon * pointers it returns point into the
 * loader's pool, NOT into a static table any more.
 *
 * Why this file was kept (instead of deleted): CMake's
 * file(GLOB_RECURSE SRC_GAME "src/game/*.c") would not need it after the
 * deletion either, but leaving the file with this header preserves a
 * grep-friendly trail from the historical symbol names back to the
 * design + commit ledger:
 *
 *   Design: context/designs/catalog/catalog-full-pipeline-weapons.md
 *   F11 (extractor + JSON):       commit 41ccbfed
 *   F12 (loader + manager pool):  commits d7994583 612e5d54 57197d98 69abadbd 5285b8e6
 *   F12.3-F12.4 (deploy fix):     commits 4f6c1dd6 534ff172
 *   F13 (Layer A retire):         this commit
 *
 * If you found this file because you grep'd for invitem_X or g_Weapons
 * after upgrading: every consumer migrated through F2-F8 (S484) to use
 * the catalog manager API in port/include/catalog_mgr_weapons.h. The
 * accessor for index-by-WEAPON_* enum is catalogManagerGetWeaponByIndex();
 * use that instead.
 */
