/*
 * tests/test_loader_pdbase_scan.cpp -- S484 F10 + F11 pin the .pdbase
 * loader scaffold and the generated base/weapons.pdbase archive.
 *
 * F10 state: loader is a scaffold that only emits a LOADER.PDBASE.WEAPON.OK
 * log line (port/src/loader_pdbase.c). API contract pins live in this file.
 *
 * F11 state: base/weapons.pdbase is now a real archive containing 86
 * weapon records + 110 animation records, generated by
 * devtools/extract_weapons_pdbase.py from src/game/invitems.c +
 * src/game/botinv.c (see context/designs/catalog/catalog-full-pipeline-weapons.md
 * Section J for the Path B (data-driven animations) decision and
 * Section C for the JSON schema).
 *
 * F12 will add a real C-side JSON parser + opcode codec; the round-trip
 * field-equivalence test against the live g_Weapons[] data lives there.
 * This file pins the generated archive's structural invariants so the
 * extractor cannot silently regress between sessions.
 *
 * Source under test:
 *   port/src/loader_pdbase.c (scaffold, not linked in pd-tests).
 *   base/weapons.pdbase (generated artifact committed alongside the
 *     extractor; structure pinned here via raw-text checks).
 */

#include "catch.hpp"

#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string readFile(const char *path) {
    std::ifstream in(path, std::ios::in | std::ios::binary);
    REQUIRE(in.good());
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

/* Count occurrences of a literal substring. Used to count records by
 * pinning the unique field shape that appears once per record. */
size_t countSubstring(const std::string &haystack, const std::string &needle) {
    size_t count = 0;
    size_t pos = 0;
    while ((pos = haystack.find(needle, pos)) != std::string::npos) {
        ++count;
        pos += needle.size();
    }
    return count;
}

}  /* anonymous namespace */

/* ---------- F10 scaffold contract ---------- */

TEST_CASE("F10: loader_pdbase.h declares the scaffold API",
          "[catalog-mgr-weapon][s484][f10]") {
    std::string hdr = readFile("port/include/loader_pdbase.h");
    REQUIRE(hdr.find("loaderPdbaseScan") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseBuildWeaponManager") != std::string::npos);
    REQUIRE(hdr.find("loader_pdbase_result_t") != std::string::npos);
}

TEST_CASE("F10: result struct carries the documented count fields",
          "[catalog-mgr-weapon][s484][f10]") {
    std::string hdr = readFile("port/include/loader_pdbase.h");
    REQUIRE(hdr.find("archives_scanned") != std::string::npos);
    REQUIRE(hdr.find("weapons_registered") != std::string::npos);
    REQUIRE(hdr.find("scan_failures") != std::string::npos);
    REQUIRE(hdr.find("resolve_failures") != std::string::npos);
    REQUIRE(hdr.find("field_unknown") != std::string::npos);
}

TEST_CASE("F10: loader emits LOADER.PDBASE.WEAPON.* log channels",
          "[catalog-mgr-weapon][s484][f10]") {
    std::string src = readFile("port/src/loader_pdbase.c");
    /* Per-directive hierarchical channel naming is exercised by the
     * Phase 2 scaffold so end-to-end logs already have the right
     * prefix when F11+ wires the decoder in. */
    REQUIRE(src.find("LOADER.PDBASE.WEAPON.OK") != std::string::npos);
}

/* ---------- F11 generated archive structural pins ---------- */

TEST_CASE("F11: base/weapons.pdbase exists with the documented envelope",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    REQUIRE(pdbase.find("\"pdbase_version\": 1") != std::string::npos);
    REQUIRE(pdbase.find("\"type\": \"weapons\"") != std::string::npos);
    REQUIRE(pdbase.find("\"animations\":") != std::string::npos);
    REQUIRE(pdbase.find("\"weapons\":") != std::string::npos);
}

TEST_CASE("F11: archive carries 86 weapon records",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* Each weapon record carries exactly one "weapon_id": <int> field
     * by construction (see emit_weapon in extract_weapons_pdbase.py).
     * Pin the count to 86 = WEAPON_SUICIDEPILL + 1 (0x55 + 1). */
    size_t count = countSubstring(pdbase, "\"weapon_id\":");
    REQUIRE(count == 86);
}

TEST_CASE("F11: archive carries 110 animation records",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* Each animation has a unique "id": "invanim_..." line; weapons
     * carry "id": "base:..." instead. Counting "invanim_" inside a
     * "id": ... string yields the animation count exactly because
     * weapon-side anim refs use bare strings without the "id":
     * prefix. */
    size_t count = countSubstring(pdbase, "\"id\": \"invanim_");
    REQUIRE(count == 110);
}

TEST_CASE("F11: known weapon catalog ids are present",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* Spot-check anchor IDs that mark structural completeness:
     *   nothing/unarmed (slots 0-1), falcon2 (slot 2 = WEAPON_FALCON2),
     *   eyespy variants (camspy/xrayscanner), and suicidepill (slot 0x55). */
    REQUIRE(pdbase.find("\"id\": \"base:nothing\"") != std::string::npos);
    REQUIRE(pdbase.find("\"id\": \"base:unarmed\"") != std::string::npos);
    REQUIRE(pdbase.find("\"id\": \"base:falcon2\"") != std::string::npos);
    REQUIRE(pdbase.find("\"id\": \"base:camspy\"") != std::string::npos);
    REQUIRE(pdbase.find("\"id\": \"base:suicidepill\"") != std::string::npos);
}

TEST_CASE("F11: opcode mnemonics use the documented vocabulary",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* The 12 mnemonics map 1:1 to the gunscript_* macros in
     * src/include/gunscript.h. F12's opcode decoder will reverse this
     * mapping to GUNCMD_* enum values. Pin every mnemonic so a
     * regression that drops one (e.g. by silently producing
     * "unknown_macro" entries) fails here. */
    REQUIRE(pdbase.find("\"end\"") != std::string::npos);
    REQUIRE(pdbase.find("\"showpart\"") != std::string::npos);
    REQUIRE(pdbase.find("\"hidepart\"") != std::string::npos);
    REQUIRE(pdbase.find("\"waittime\"") != std::string::npos);
    REQUIRE(pdbase.find("\"playsound\"") != std::string::npos);
    REQUIRE(pdbase.find("\"include\"") != std::string::npos);
    REQUIRE(pdbase.find("\"random\"") != std::string::npos);
    REQUIRE(pdbase.find("\"playanimation\"") != std::string::npos);
    /* No "unknown_macro" leaks: the extractor must understand every
     * gunscript_* and gunviscmd_* call in invitems.c. A regression that
     * adds a new macro to gunscript.h without updating the extractor
     * fails here (loud, structural). */
    REQUIRE(pdbase.find("unknown_macro") == std::string::npos);
}

TEST_CASE("F11: gunviscmd mnemonics are present",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* Per-weapon "gunviscmds" arrays use the gunviscmd_* macro
     * vocabulary. sethidden is the most common; checkupgrade /
     * checkinlefthand / checkinrighthand are also used by some weapons. */
    REQUIRE(pdbase.find("\"sethidden\"") != std::string::npos);
}

TEST_CASE("F11: every weapon record carries a bot_pref sub-struct",
          "[catalog-mgr-weapon][s484][f11]") {
    std::string pdbase = readFile("base/weapons.pdbase");
    /* The bot AI preference table (g_AibotWeaponPreferences[] in
     * src/game/botinv.c) folds into each weapon as the bot_pref
     * sub-struct per the F7 manager API contract. The extractor pulls
     * it from botinv.c and emits one bot_pref per weapon. Pin the
     * count to 86. */
    size_t count = countSubstring(pdbase, "\"bot_pref\":");
    REQUIRE(count == 86);
}

TEST_CASE("F11: extractor script is committed alongside the archive",
          "[catalog-mgr-weapon][s484][f11]") {
    /* The .pdbase file is a generated artifact. The script that
     * generates it must be committed alongside so regeneration is
     * reproducible. Pin existence + key API surface. */
    std::string script = readFile("devtools/extract_weapons_pdbase.py");
    REQUIRE(script.find("S484 F11") != std::string::npos);
    REQUIRE(script.find("emit_weapon") != std::string::npos);
    REQUIRE(script.find("emit_animation") != std::string::npos);
    REQUIRE(script.find("GUNSCRIPT_MACROS") != std::string::npos);
    REQUIRE(script.find("GUNVISCMD_MACROS") != std::string::npos);
}

/* ---------- F12 loader API contract ---------- */

TEST_CASE("F12+F13: loader_pdbase.h declares pool API",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string hdr = readFile("port/include/loader_pdbase.h");
    /* Pool accessor + activity probe pinned by the manager swap. */
    REQUIRE(hdr.find("loaderPdbaseIsActive") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseGetWeapon") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseGetDefaultAim") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseGetDefaultNoise") != std::string::npos);
    /* F13 added: bot_pref accessor (replaces g_AibotWeaponPreferences). */
    REQUIRE(hdr.find("loaderPdbaseGetBotPref") != std::string::npos);
    /* Round-trip helper for opcode encoding (used by future tests). */
    REQUIRE(hdr.find("loaderPdbaseEncodeOpcode") != std::string::npos);
    /* F13 retired: parity self-test (no g_Weapons[] to compare against). */
    REQUIRE(hdr.find("loaderPdbaseRunParityCheck") == std::string::npos);
}

TEST_CASE("F12+F13: loader implementation emits documented log channels",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string src = readFile("port/src/loader_pdbase.c");
    /* Four hierarchical channels remain after F13 (PARITY_FAIL gone with
     * the parity-check function). */
    REQUIRE(src.find("LOADER.PDBASE.WEAPON.OK") != std::string::npos);
    REQUIRE(src.find("LOADER.PDBASE.WEAPON.SCAN_FAIL") != std::string::npos);
    REQUIRE(src.find("LOADER.PDBASE.WEAPON.RESOLVE_FAIL") != std::string::npos);
    REQUIRE(src.find("LOADER.PDBASE.WEAPON.POOL_FULL") != std::string::npos);
}

TEST_CASE("F12: opcode codec covers all 12 GUNCMD_* mnemonics",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string src = readFile("port/src/loader_pdbase.c");
    /* Every mnemonic in src/include/gunscript.h must round-trip. The
     * encoder switch and decoder if-chain both name the mnemonic, so
     * the literal is in the source twice per opcode. Pin it once
     * here per opcode -- the decoder branch. */
    const char *mnemonics[] = {
        "\"end\"", "\"showpart\"", "\"hidepart\"", "\"waitforzreleased\"",
        "\"waittime\"", "\"playsound\"", "\"include\"", "\"random\"",
        "\"repeatuntilfull\"", "\"popoutsackofpills\"", "\"playanimation\"",
        "\"setsoundspeed\"",
    };
    for (const char *m : mnemonics) {
        REQUIRE(src.find(m) != std::string::npos);
    }
}

TEST_CASE("F12+F13: manager accessor routes through loader (no fallback)",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string mgr = readFile("port/src/catalog_mgr_weapons.c");
    /* The integer-index path returns loader-owned pointers. F13
     * removed the parity-period fallback to g_Weapons[]: there must
     * be NO references to g_Weapons in the manager source. */
    REQUIRE(mgr.find("loaderPdbaseGetWeapon") != std::string::npos);
    REQUIRE(mgr.find("loaderPdbaseGetDefaultAim") != std::string::npos);
    REQUIRE(mgr.find("loaderPdbaseGetDefaultNoise") != std::string::npos);
    REQUIRE(mgr.find("loaderPdbaseGetBotPref") != std::string::npos);
    /* F13: the legacy externs / fallback are gone. */
    REQUIRE(mgr.find("g_Weapons[") == std::string::npos);
    REQUIRE(mgr.find("g_AibotWeaponPreferences") == std::string::npos);
    REQUIRE(mgr.find("invaimsettings_default") == std::string::npos);
    REQUIRE(mgr.find("invnoisesettings_silent") == std::string::npos);
}

TEST_CASE("F12+F13: loader is wired into client startup",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string main_src = readFile("port/src/main.c");
    /* main.c must call the loader scan + build sequence right after
     * assetCatalogRegisterBaseGame(). F13 dropped the parity check
     * call from this sequence (parity check function retired). */
    REQUIRE(main_src.find("loaderPdbaseScan") != std::string::npos);
    REQUIRE(main_src.find("loaderPdbaseBuildWeaponManager") != std::string::npos);
    REQUIRE(main_src.find("loaderPdbaseRunParityCheck") == std::string::npos);
}

TEST_CASE("F12: enum lookup tables exist for ANIM/SFX/FILE/L_GUN",
          "[catalog-mgr-weapon][s484][f12]") {
    std::string hdr = readFile("port/include/loader_pdbase_enums.h");
    REQUIRE(hdr.find("loaderPdbaseResolveAnimEnum") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseResolveSfxEnum") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseResolveLangEnum") != std::string::npos);
    REQUIRE(hdr.find("loaderPdbaseResolveFileEnum") != std::string::npos);
    /* The generated table file must exist and carry sensible counts. */
    std::string gen = readFile("port/src/loader_pdbase_enums.c");
    REQUIRE(gen.find("k_AnimEnum[]") != std::string::npos);
    REQUIRE(gen.find("k_SfxEnum[]") != std::string::npos);
    REQUIRE(gen.find("k_LangEnum[]") != std::string::npos);
    REQUIRE(gen.find("k_FileEnum[]") != std::string::npos);
}

/* ---------- F13 grep-guard: Layer A symbols are gone from source ---------- */

/* Helper: does the file contain a non-comment occurrence of `needle`?
 * We approximate "non-comment" by stripping out lines whose first
 * non-whitespace char is `//` or `*` and lines that include `* ` (a
 * block-comment continuation marker). Imperfect but catches the
 * comment-vs-definition split for the F13 grep guard. */
static bool fileHasNonCommentOccurrence(const std::string &src,
                                          const std::string &needle) {
    size_t pos = 0;
    while ((pos = src.find(needle, pos)) != std::string::npos) {
        /* Find the start of this line. */
        size_t lineStart = src.rfind('\n', pos);
        lineStart = (lineStart == std::string::npos) ? 0 : lineStart + 1;
        /* Walk forward to the first non-space char on this line. */
        size_t i = lineStart;
        while (i < src.size() && (src[i] == ' ' || src[i] == '\t')) i++;
        bool isComment = false;
        if (i + 1 < src.size()) {
            if (src[i] == '/' && src[i + 1] == '/') isComment = true;
            else if (src[i] == '*') isComment = true;
            else if (src[i] == '/' && src[i + 1] == '*') isComment = true;
        }
        if (!isComment) return true;
        pos += needle.size();
    }
    return false;
}

TEST_CASE("F13: invitems.c no longer defines the static records",
          "[catalog-mgr-weapon][s484][f13]") {
    std::string src = readFile("src/game/invitems.c");
    /* The file is reduced to a header comment after F13. Look for
     * non-comment occurrences of the historical symbol patterns. */
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "g_Weapons["));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "struct weapon invitem_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invfunc_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invammo_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invaimsettings_default"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invnoisesettings_silent"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invrecoilsettings_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "struct guncmd invanim_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "struct gunviscmd gunviscmds_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "invpartvisibility_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "vibrationstart_"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "vibrationmax_"));
}

TEST_CASE("F13: botinv.c no longer defines g_AibotWeaponPreferences",
          "[catalog-mgr-weapon][s484][f13]") {
    std::string src = readFile("src/game/botinv.c");
    /* The table definition is fully removed. Header-comment mention of
     * the symbol name is fine. */
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "g_AibotWeaponPreferences["));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(src, "BOTDISTCFG_PISTOL,"));
}

TEST_CASE("F13: extern declarations are gone from headers",
          "[catalog-mgr-weapon][s484][f13]") {
    std::string inv_h  = readFile("src/include/game/inv.h");
    std::string data_h = readFile("src/include/data.h");
    REQUIRE_FALSE(fileHasNonCommentOccurrence(inv_h,
        "extern struct weapon *g_Weapons["));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(inv_h,
        "extern struct invaimsettings invaimsettings_default"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(inv_h,
        "extern struct noisesettings invnoisesettings_silent"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(data_h,
        "extern struct weapon *g_Weapons["));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(data_h,
        "extern struct aibotweaponpreference g_AibotWeaponPreferences["));
}

TEST_CASE("F13: no consumer references remain in src/game or port/src",
          "[catalog-mgr-weapon][s484][f13]") {
    /* This pin doesn't grep the whole tree -- it samples the files
     * known to have been consumers prior to F2-F8. The build itself
     * is the most reliable guard (link errors if a symbol is referenced
     * but undefined), but pinning specific files makes a regression
     * obvious in the test diff. */
    std::string player_c = readFile("src/game/player.c");
    REQUIRE_FALSE(fileHasNonCommentOccurrence(player_c, "ARRAYCOUNT(g_Weapons)"));
    REQUIRE_FALSE(fileHasNonCommentOccurrence(player_c, "g_Weapons["));

    std::string game_0b0fd0_c = readFile("src/game/game_0b0fd0.c");
    /* Comments mentioning g_Weapons are fine; live references are not. */
    REQUIRE_FALSE(fileHasNonCommentOccurrence(game_0b0fd0_c, "g_Weapons["));
}
