/*
 * tests/test_loader_pdbase_arenas.cpp -- Catalog Gate 3 Arenas F11 +
 * F12: pin the .pdbase loader's arenas-side scaffold + parser + parity
 * check.
 *
 * F11 state: base/arenas.pdbase contains 47 records generated by
 * devtools/extract_arenas_pdbase.py from src/game/mplayer/setup.c
 * + port/src/assetcatalog_base.c + src/include/constants.h. STAGE_*
 * and L_* symbolic names are resolved to integers at extract time
 * (Path B decision); slug + category + id + load_mode stay strings.
 *
 * F12 state: port/src/loader_pdbase.c gains parseArena +
 * parseTopLevel "arenas" dispatcher + loaderPdbaseRunParityCheckArenas.
 * Manager s_get checks loaderPdbaseArenasActive() and copies the
 * loader-owned record into the manager pool (catalog_mgr_arenas.c).
 *
 * Source under test:
 *   base/arenas.pdbase (generated artifact)
 *   port/src/loader_pdbase.c (parser + parity check)
 *   port/src/catalog_mgr_arenas.c (manager bridge)
 *   port/src/main.c (init order: build manager + parity check)
 */

#include "catch.hpp"

#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string readFile(const char *path) {
	std::ifstream in(path, std::ios::in | std::ios::binary);
	REQUIRE(in.good());
	std::ostringstream ss;
	ss << in.rdbuf();
	return ss.str();
}

size_t countSubstring(const std::string &haystack, const std::string &needle) {
	size_t count = 0;
	size_t pos = 0;
	while ((pos = haystack.find(needle, pos)) != std::string::npos) {
		++count;
		pos += needle.size();
	}
	return count;
}

}  /* anonymous namespace */

/* ========================================================================
 * F11 archive structural invariants.
 * ======================================================================== */

TEST_CASE("loader-pdbase-arenas: archive exists + envelope",
          "[catalog-mgr-arena][gate3][f11]") {
	std::string src = readFile("base/arenas.pdbase");
	REQUIRE(src.find("\"pdbase_version\": 1") != std::string::npos);
	REQUIRE(src.find("\"type\": \"arenas\"") != std::string::npos);
	REQUIRE(src.find("\"arenas\":") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: 47 records with arena_index",
          "[catalog-mgr-arena][gate3][f11]") {
	std::string src = readFile("base/arenas.pdbase");
	/* "arena_index" appears once per arena record. */
	REQUIRE(countSubstring(src, "\"arena_index\":") == 47);
}

TEST_CASE("loader-pdbase-arenas: sample IDs present",
          "[catalog-mgr-arena][gate3][f11]") {
	std::string src = readFile("base/arenas.pdbase");
	/* One per category from s_ArenaGroupMap[5]. */
	REQUIRE(src.find("\"id\": \"base:arena_mp_skedar\"") != std::string::npos);  /* Dark */
	REQUIRE(src.find("\"id\": \"base:arena_defection\"") != std::string::npos);  /* Solo Missions */
	REQUIRE(src.find("\"id\": \"base:arena_mp_temple\"") != std::string::npos);  /* Classic */
	REQUIRE(src.find("\"id\": \"base:arena_test_lam\"") != std::string::npos);   /* Bonus -- Grand Library */
	REQUIRE(src.find("\"id\": \"base:arena_mp_random_multi\"") != std::string::npos);
	REQUIRE(src.find("\"id\": \"base:arena_mp_random_solo\"") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: load_mode invariants",
          "[catalog-mgr-arena][gate3][f11]") {
	std::string src = readFile("base/arenas.pdbase");
	/* All Solo Missions arenas (14 records, arena_index 13..26) carry
	 * ARENA_LOADMODE_CANVAS. The other 33 carry ARENA_LOADMODE_PLAYABLE. */
	REQUIRE(countSubstring(src, "\"load_mode\": \"ARENA_LOADMODE_CANVAS\"") == 14);
	REQUIRE(countSubstring(src, "\"load_mode\": \"ARENA_LOADMODE_PLAYABLE\"") == 47 - 14);
}

TEST_CASE("loader-pdbase-arenas: category counts match s_ArenaGroupMap",
          "[catalog-mgr-arena][gate3][f11]") {
	std::string src = readFile("base/arenas.pdbase");
	REQUIRE(countSubstring(src, "\"category\": \"Dark\"") == 13);
	REQUIRE(countSubstring(src, "\"category\": \"Solo Missions\"") == 14);
	REQUIRE(countSubstring(src, "\"category\": \"Classic\"") == 5);
	REQUIRE(countSubstring(src, "\"category\": \"Bonus\"") == 13);
	REQUIRE(countSubstring(src, "\"category\": \"Random\"") == 2);
}

/* ========================================================================
 * F12 parser + parity-check structural invariants.
 *
 * Static-text grep against port/src/loader_pdbase.c so a future edit
 * cannot silently drop the parser or the parity check.
 * ======================================================================== */

TEST_CASE("loader-pdbase-arenas: parseArena exists",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/loader_pdbase.c");
	REQUIRE(src.find("static void parseArena(jstream_t *s)") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: parseTopLevel dispatches arenas key",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/loader_pdbase.c");
	REQUIRE(src.find("jstream_str_eq(&key, \"arenas\")") != std::string::npos);
	REQUIRE(src.find("parseArena(s)") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: parity check function exists",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/loader_pdbase.c");
	REQUIRE(src.find("loaderPdbaseRunParityCheckArenas(void)") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: log channels present",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/loader_pdbase.c");
	REQUIRE(src.find("LOADER.PDBASE.ARENA.SCAN_FAIL") != std::string::npos);
	REQUIRE(src.find("LOADER.PDBASE.ARENA.RESOLVE_FAIL") != std::string::npos);
	REQUIRE(src.find("LOADER.PDBASE.ARENA.FIELD_UNKNOWN") != std::string::npos);
	REQUIRE(src.find("LOADER.PDBASE.ARENA.OK") != std::string::npos);
	REQUIRE(src.find("LOADER.PDBASE.ARENA.PARITY_FAIL") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: load_mode inline resolver covers both values",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/loader_pdbase.c");
	REQUIRE(src.find("ARENA_LOADMODE_PLAYABLE") != std::string::npos);
	REQUIRE(src.find("ARENA_LOADMODE_CANVAS") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: manager s_get checks loader active flag",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/catalog_mgr_arenas.c");
	REQUIRE(src.find("loaderPdbaseArenasActive()") != std::string::npos);
	REQUIRE(src.find("loaderPdbaseGetArena(") != std::string::npos);
}

TEST_CASE("loader-pdbase-arenas: main.c wires build + parity check",
          "[catalog-mgr-arena][gate3][f12]") {
	std::string src = readFile("port/src/main.c");
	REQUIRE(src.find("loaderPdbaseBuildArenaManager()") != std::string::npos);
	REQUIRE(src.find("loaderPdbaseRunParityCheckArenas()") != std::string::npos);
	REQUIRE(src.find("catalogManagerArenaInit()") != std::string::npos);
}
