/**
 * romextract_pdsfx.c -- Catalog universality pivot Step 3 audio half
 * (2026-05-03). Owns the shared SFX-bank walker used by both .pdsfx
 * and .pdvoice emitters.
 *
 * Walks the leaf SFX bank exposed via the disk-migrated sfxctl and
 * sfxtbl segments and emits one .pdsfx ZIP compound per leaf sound
 * NOT classified as voice (.pdvoice -- see romextract_pdvoice.c --
 * uses the same walker with PDAUDIO_WALK_VOICE).
 *
 * Per-asset ZIP layout:
 *   sound.ini / voice.ini  editable audio descriptor
 *   _meta/manifest.json    compatibility envelope + provenance
 *   _meta/*.json           shared inventory/provenance/validation/source handles
 *   sample.wav             decoded mono PCM16 WAV
 *   _meta/*.sha256         public-file SHA-256 sidecars
 *
 * Catalog ID convention: .pdsfx and .pdvoice use symbolic/readable
 * base:sfx_* and base:voice_* IDs generated by catalog_readable_ids.
 * Numeric SFX indices remain descriptor/provenance metadata only.
 *
 * Voice classification (Q-2 type-tolerance + Slice 10 predicate):
 *   A leaf SFX index `i` is classified as voice if some russ entry
 *   in g_AudioRussMappings[] has soundnum==i AND audioconfig_index
 *   in {1, 2, 3, 47, 48, 60, 62}. The same predicate gates the
 *   .pdvoice walk in romextract_pdvoice.c -- the two filters are
 *   complementary so every leaf goes to exactly one emitter.
 *
 * Server build (PD_SERVER): no audio segments populated, no russ
 * table linkage (snd.c is not in the server build), so the walker
 * short-circuits to 0 on entry.
 *
 * Companion docs:
 *   context/designs/catalog/universality-pivot-schemas.md   schemas
 *   context/audits/catalog-universality-pivot-plan-2026-05-02.md  plan
 *   context/audits/catalog-phase3-slice10-voice-retag-2026-05-02.md
 *                                              voice-classification basis
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <SDL.h>
#include <PR/ultratypes.h>
#include <PR/libaudio.h>

#include "boot_pool.h"
#include "boot_progress.h"
#include "catalog_readable_ids.h"
#include "data.h"
#include "types.h"
#include "constants.h"
#include "fs.h"
#include "loader_enum_reverse.h"
#include "asset_archive_writer.h"
#include "modarchive.h"
#include "romdata.h"
#include "romextract.h"
#include "romextract_pd.h"
#include "romextract_pdaudio_internal.h"
#include "system.h"

/* Runtime-channel form of sysLoudFailf. The system.h macro requires a
 * string literal for klass so it can do compile-time concatenation;
 * our shared walker switches between "EXTRACT.PDSFX" and
 * "EXTRACT.PDVOICE" at runtime, so we build an equivalent expansion
 * with %s for the channel name. Same LOG_WARNING level + "LOUDFAIL."
 * prefix; same single sysLogPrintf surface for log filters to grep.
 *
 * The ##__VA_ARGS__ GNU extension elides the leading comma when no
 * variadic args are passed (e.g. LOUD_FAILF_RT(ch, "msg"); has no
 * trailing comma artifact). GCC supports it; this codebase already
 * builds under GCC/MinGW so the extension is available. */
#define LOUD_FAILF_RT(channel, fmt, ...) \
	sysLogPrintf(LOG_WARNING, "LOUDFAIL.%s: " fmt, channel, ##__VA_ARGS__)

/* The bank file format is described in include/PR/libaudio.h plus
 * the post-preprocess form in port/src/preprocess/segaudio.c. Stored
 * pointer fields are (uintptr_t)-cast offsets into the same sfxctl
 * buffer, which is what makes "treat the buffer as raw bytes and add
 * offset" the right read pattern below. */
#define PDSFX_OUT_DIR_SFX   "audio/sfx"
#define PDSFX_OUT_DIR_VOICE "audio/voice"

/* Audioconfig slot numbers that the Slice 10 retag classifies as
 * voice. Mirrors s_audioConfigIsVoice() in
 * port/src/assetcatalog_base_extended.c -- kept in lockstep with that
 * predicate so audio classification is consistent between catalog
 * registration and per-asset extraction. */
#ifndef AUDIOCONFIG_01
#define AUDIOCONFIG_01 1
#define AUDIOCONFIG_02 2
#define AUDIOCONFIG_03 3
#define AUDIOCONFIG_47 47
#define AUDIOCONFIG_48 48
#define AUDIOCONFIG_60 60
#define AUDIOCONFIG_62 62
#endif

#if !defined(PD_SERVER)

static s32 s_audioConfigIsVoice(s32 idx)
{
	switch (idx) {
	case AUDIOCONFIG_01:
	case AUDIOCONFIG_02:
	case AUDIOCONFIG_03:
	case AUDIOCONFIG_47:
	case AUDIOCONFIG_48:
	case AUDIOCONFIG_60:
#if VERSION >= VERSION_NTSC_1_0
	case AUDIOCONFIG_62:
#endif
		return 1;
	default:
		return 0;
	}
}

/* Locate a named segment buffer + size. Returns 1 on success, 0 on
 * miss. Mirrors the s_findAnimSegment helper in
 * romextract_pdanim_chr.c. */
static s32 s_findSegment(const char *name, const u8 **outData, u32 *outSize)
{
	*outData = NULL;
	*outSize = 0;
	if (!name) return 0;

	s32 nseg = romdataSegmentCount();
	for (s32 i = 0; i < nseg; i++) {
		const char *seg_name = romdataSegmentGetName(i);
		if (seg_name && strcmp(seg_name, name) == 0) {
			const u8 *data = romdataSegmentGetData(i);
			u32 size = romdataSegmentGetSize(i);
			if (!data || size == 0) return 0;
			*outData = data;
			*outSize = size;
			return 1;
		}
	}
	return 0;
}

/* Lowercase + strip the leading "SFX_" so an enum like
 * "SFX_LAUNCH_ROCKET" becomes "sfx_launch_rocket" -- the catalog ID
 * format from feedback_human_readable_ids. Output is written into
 * out_buf, which must hold at least out_n bytes. */
/* Build the catalog ID for a given SFX index in either sfx or voice
 * mode. Returns 1 if a symbolic name was available, 0 when a readable
 * generated fallback was needed. */
static s32 s_buildSfxCatalogId(s32 sfx_idx, pdaudio_walk_mode_t mode,
                                char *out, size_t out_n)
{
	const char *sym = loaderEnumNameForSfxEnum(sfx_idx);
	if (mode == PDAUDIO_WALK_SFX) {
		catalogReadableSfxId(sfx_idx, out, out_n);
		return sym && sym[0] ? 1 : 0;
	}

	catalogReadableVoiceId(sfx_idx, out, out_n);
	return sym && sym[0] ? 1 : 0;
}

/* Filename slug: catalog ID with ':' replaced by '_'. */
static void s_filenameSlug(const char *catalog_id, char *out, size_t out_n)
{
	size_t i, j = 0;
	for (i = 0; catalog_id[i] && j + 1 < out_n; i++) {
		out[j++] = (catalog_id[i] == ':') ? '_' : catalog_id[i];
	}
	out[j] = '\0';
}

static s32 s_existingArchiveHasEntry(const char *relpath, const char *entry);
static s32 s_existingArchiveEntryContains(const char *relpath,
                                          const char *entry,
                                          const char *needle);

static s32 s_configuredAliasMappedMp3Source(s32 confignum, union soundnumhack *out)
{
	if (confignum < 0 || confignum >= g_NumAudioRussMappings) {
		return 0;
	}

	union soundnumhack mapped;
	mapped.packed = g_AudioRussMappings[confignum].soundnum;
	if (out) {
		*out = mapped;
	}
	return mapped.mp3priority != 0;
}

static s32 s_configuredAliasArchivesComplete(const char *out_dir)
{
	if (!out_dir || !out_dir[0]) return 0;
	for (s32 r = 0; r < g_NumAudioRussMappings; r++) {
		union soundnumhack ref;
		ref.packed = 0;
		ref.hasconfig = 1;
		ref.confignum = (u16)r;
		s32 packed = (s32)(u16)ref.packed;
		if (!loaderEnumNameForSfxEnum(packed)) {
			continue;
		}
		if (s_configuredAliasMappedMp3Source(r, NULL)) {
			continue;
		}
		char catalog_id[128];
		char slug[128];
		char full[FS_MAXPATH];
		catalogReadableSoundRefId(packed, catalog_id, sizeof(catalog_id));
		s_filenameSlug(catalog_id, slug, sizeof(slug));
		snprintf(full, sizeof(full), "%s/%s.pdsfx", out_dir, slug);
		if (fsFileSize(full) <= 0) {
			return 0;
		}
	}
	return 1;
}

static s32 s_configuredMp3VoiceArchivesComplete(const char *out_dir)
{
	if (!out_dir || !out_dir[0]) return 0;
	for (s32 r = 0; r < g_NumAudioRussMappings; r++) {
		union soundnumhack ref;
		ref.packed = 0;
		ref.hasconfig = 1;
		ref.confignum = (u16)r;
		s32 packed = (s32)(u16)ref.packed;
		if (!loaderEnumNameForSfxEnum(packed)) {
			continue;
		}
		if (!s_configuredAliasMappedMp3Source(r, NULL)) {
			continue;
		}
		char catalog_id[128];
		char slug[128];
		char full[FS_MAXPATH];
		catalogReadableSoundRefId(packed, catalog_id, sizeof(catalog_id));
		s_filenameSlug(catalog_id, slug, sizeof(slug));
		snprintf(full, sizeof(full), "%s/%s.pdvoice", out_dir, slug);
		if (fsFileSize(full) <= 0 ||
				!s_existingArchiveHasEntry(full, "voice.ini") ||
				!s_existingArchiveHasEntry(full, "_meta/manifest.json") ||
				!s_existingArchiveHasEntry(full, "sample.mp3") ||
				!s_existingArchiveEntryContains(full, "_meta/manifest.json",
					"\"source_filenum\"")) {
			return 0;
		}
	}
	return 1;
}

/* Read offset out of a stored "pointer" field in the post-preprocess
 * bank buffer. The preprocess stage casts u32 offsets to void* via
 * uintptr_t; we round-trip the same conversion here. */
static u32 s_offsetFromPointer(void *p)
{
	return (u32)(uintptr_t)p;
}

/* Pre-build a bitset cache that flags which leaf SFX indices map to
 * a voice audioconfig slot. The russ table has 444 entries (less
 * than the 1545 leaf SFX); flag once at start of walk so the
 * per-sound check is O(1).
 *
 * c106 fix (2026-05-13): russ->soundnum is a PACKED bitfield (see
 * `union soundnumhack` in src/include/types.h:3484). The leaf SFX
 * bank index is in the 11-bit `id` subfield, NOT the raw s16 value.
 * Raw values often exceed s16 range (e.g. 0x977a -> -26758 as s16)
 * and were being rejected by the `sfx_idx >= 0` guard, leaving the
 * cache all zero. Mike's playtest log showed `pdvoice skipped=1545`
 * (every sound classified is_voice=0) for this reason. Unpacking via
 * the union exposes the real leaf index. The audioconfig_index field
 * is still consulted from the raw struct (it is a normal u16). */
static void s_buildVoiceCache(u8 *cache, u32 cache_n)
{
	memset(cache, 0, cache_n);
	const s32 russ_n = g_NumAudioRussMappings;
	for (s32 i = 0; i < russ_n; i++) {
		s32 cfg = (s32)g_AudioRussMappings[i].audioconfig_index;
		if (!s_audioConfigIsVoice(cfg)) continue;
		union soundnumhack hack;
		hack.packed = g_AudioRussMappings[i].soundnum;
		s32 sfx_idx = (s32)hack.id;
		if ((u32)sfx_idx < cache_n) {
			cache[sfx_idx] = 1;
		}
	}
}

/* Wave format string per ALWaveTable.type. The ROM's two formats are
 * AL_ADPCM_WAVE (compressed; SFX bank's normal format) and
 * AL_RAW16_WAVE (uncompressed PCM16). The schema's "OGG_REPLACEMENT"
 * is reserved for mod-supplied sample replacement; base extraction
 * never produces it. */
static const char *s_waveFormatString(u8 type)
{
	switch (type) {
	case AL_ADPCM_WAVE: return "ALADPCM";
	case AL_RAW16_WAVE: return "PCM16";
	default:            return "UNKNOWN";
	}
}

static s16 s_clip16(s32 value)
{
	if (value < -32768) return -32768;
	if (value > 32767) return 32767;
	return (s16)value;
}

static void s_writeLe16(u8 *dst, u16 value)
{
	dst[0] = (u8)(value & 0xff);
	dst[1] = (u8)((value >> 8) & 0xff);
}

static void s_writeLe32(u8 *dst, u32 value)
{
	dst[0] = (u8)(value & 0xff);
	dst[1] = (u8)((value >> 8) & 0xff);
	dst[2] = (u8)((value >> 16) & 0xff);
	dst[3] = (u8)((value >> 24) & 0xff);
}

static s32 s_validateAdpcmBook(const u8 *ctl_data, u32 ctl_size,
                               const ALADPCMBook *book)
{
	u32 book_off = s_offsetFromPointer((void *)book);
	if (book_off == 0 || book_off + 8 > ctl_size) return 0;
	const ALADPCMBook *resolved = (const ALADPCMBook *)(ctl_data + book_off);
	if (resolved->order <= 0 || resolved->order > 2) return 0;
	if (resolved->npredictors <= 0 || resolved->npredictors > 8) return 0;
	u32 entries = (u32)resolved->order * (u32)resolved->npredictors * 8u;
	if (book_off + 8u + entries * 2u > ctl_size) return 0;
	return 1;
}

static const ALADPCMBook *s_resolveAdpcmBook(const u8 *ctl_data, u32 ctl_size,
                                             const ALADPCMBook *book)
{
	if (!s_validateAdpcmBook(ctl_data, ctl_size, book)) return NULL;
	return (const ALADPCMBook *)(ctl_data + s_offsetFromPointer((void *)book));
}

static void s_decodeAdpcmFrame(const u8 *frame, const ALADPCMBook *book,
                               s16 state[16], s16 out[16])
{
	s32 shift = (s32)(frame[0] >> 4);
	s32 predictor = (s32)(frame[0] & 0x0f);
	if (predictor >= book->npredictors) predictor = 0;

	const s16 (*book_tbl)[8] = (const s16 (*)[8])
		&book->book[predictor * book->order * 8];
	s16 tbl[2][8];
	memset(tbl, 0, sizeof(tbl));
	for (s32 row = 0; row < book->order && row < 2; row++) {
		for (s32 col = 0; col < 8; col++) {
			tbl[row][col] = book_tbl[row][col];
		}
	}

	s16 history[32];
	for (s32 i = 0; i < 16; i++) {
		history[i] = state[i];
	}

	const u8 *in = frame + 1;
	for (s32 group = 0; group < 2; group++) {
		s16 ins[8];
		s16 prev1 = history[15 + group * 8];
		s16 prev2 = history[14 + group * 8];

		for (s32 j = 0; j < 4; j++) {
			s8 hi = (s8)((*in >> 4) & 0x0f);
			s8 lo = (s8)(*in & 0x0f);
			if (hi >= 8) hi -= 16;
			if (lo >= 8) lo -= 16;
			ins[j * 2] = (s16)((s32)hi * (1 << shift));
			ins[j * 2 + 1] = (s16)((s32)lo * (1 << shift));
			in++;
		}

		for (s32 j = 0; j < 8; j++) {
			s32 acc = tbl[0][j] * prev2 + tbl[1][j] * prev1
				+ ((s32)ins[j] << 11);
			for (s32 k = 0; k < j; k++) {
				acc += tbl[1][((j - k) - 1)] * ins[k];
			}
			out[group * 8 + j] = s_clip16(acc >> 11);
		}

		for (s32 j = 0; j < 8; j++) {
			history[16 + group * 8 + j] = out[group * 8 + j];
		}
	}

	for (s32 i = 0; i < 16; i++) {
		state[i] = out[i];
	}
}

static s32 s_buildWavPayload(const u8 *ctl_data, u32 ctl_size,
                             const ALWaveTable *wt,
                             const u8 *sample_data, u32 sample_len,
                             s32 sample_rate,
                             u8 **out_data, u32 *out_size,
                             u32 *out_sample_count)
{
	*out_data = NULL;
	*out_size = 0;
	*out_sample_count = 0;

	s16 *pcm = NULL;
	u32 pcm_count = 0;

	if (wt->type == AL_ADPCM_WAVE) {
		const ALADPCMBook *book = s_resolveAdpcmBook(
			ctl_data, ctl_size, wt->waveInfo.adpcmWave.book);
		if (!book) return 0;
		u32 frames = sample_len / 9u;
		pcm_count = frames * 16u;
		if (pcm_count == 0) return 0;
		pcm = (s16 *)malloc((size_t)pcm_count * sizeof(s16));
		if (!pcm) return 0;

		s16 state[16];
		memset(state, 0, sizeof(state));
		for (u32 f = 0; f < frames; f++) {
			s_decodeAdpcmFrame(sample_data + f * 9u, book, state,
			                   pcm + f * 16u);
		}
	} else if (wt->type == AL_RAW16_WAVE) {
		pcm_count = sample_len / 2u;
		if (pcm_count == 0) return 0;
		pcm = (s16 *)malloc((size_t)pcm_count * sizeof(s16));
		if (!pcm) return 0;

		for (u32 i = 0; i < pcm_count; i++) {
			const u8 *src = sample_data + i * 2u;
			u16 be = (u16)((u16)src[0] << 8) | src[1];
			pcm[i] = (be & 0x8000) ? (s16)((s32)be - 65536) : (s16)be;
		}
	} else {
		return 0;
	}

	u32 data_bytes = pcm_count * 2u;
	u32 wav_size = 44u + data_bytes;
	u8 *wav = (u8 *)malloc(wav_size);
	if (!wav) {
		free(pcm);
		return 0;
	}

	memcpy(wav + 0, "RIFF", 4);
	s_writeLe32(wav + 4, 36u + data_bytes);
	memcpy(wav + 8, "WAVE", 4);
	memcpy(wav + 12, "fmt ", 4);
	s_writeLe32(wav + 16, 16);
	s_writeLe16(wav + 20, 1);
	s_writeLe16(wav + 22, 1);
	s_writeLe32(wav + 24, (u32)sample_rate);
	s_writeLe32(wav + 28, (u32)sample_rate * 2u);
	s_writeLe16(wav + 32, 2);
	s_writeLe16(wav + 34, 16);
	memcpy(wav + 36, "data", 4);
	s_writeLe32(wav + 40, data_bytes);

	for (u32 i = 0; i < pcm_count; i++) {
		s_writeLe16(wav + 44u + i * 2u, (u16)pcm[i]);
	}

	free(pcm);
	*out_data = wav;
	*out_size = wav_size;
	*out_sample_count = pcm_count;
	return 1;
}

static s32 s_existingArchiveHasEntry(const char *relpath, const char *entry)
{
	char full_buf[FS_MAXPATH + 1];
	const char *full = fsFullPath(relpath, full_buf, sizeof(full_buf));
	if (!full || !full[0]) return 0;
	mod_archive_t *arc = modArchiveOpen(full);
	if (!arc) return 0;
	s32 has_entry = modArchiveFindEntry(arc, entry) >= 0;
	modArchiveClose(arc);
	return has_entry;
}

static s32 s_existingArchiveEntryContains(const char *relpath,
                                          const char *entry,
                                          const char *needle)
{
	char full_buf[FS_MAXPATH + 1];
	const char *full = fsFullPath(relpath, full_buf, sizeof(full_buf));
	if (!full || !full[0]) return 0;
	mod_archive_t *arc = modArchiveOpen(full);
	if (!arc) return 0;
	s32 idx = modArchiveFindEntry(arc, entry);
	if (idx < 0) {
		modArchiveClose(arc);
		return 0;
	}
	u32 size = 0;
	char *data = (char *)modArchiveExtractAlloc(arc, idx, &size);
	modArchiveClose(arc);
	if (!data) return 0;
	char *text = (char *)malloc((size_t)size + 1u);
	if (!text) {
		free(data);
		return 0;
	}
	memcpy(text, data, size);
	text[size] = '\0';
	s32 contains = strstr(text, needle) != NULL;
	free(text);
	free(data);
	return contains;
}

/* Emit one .pdsfx (or .pdvoice) ZIP for a given ALSound entry. Returns
 * 1 written, 0 skipped, -1 failed. */
static s32 s_emitOneSound(s32 sfx_idx,
                          const u8 *ctl_data, u32 ctl_size,
                          const u8 *tbl_data, u32 tbl_size,
                          const ALSound *snd, s32 sample_rate,
                          pdaudio_walk_mode_t mode,
                          const char *out_dir, s32 force_rewrite,
                          const char *channel,
                          const char *catalog_id_override,
                          const char *source_symbol_override)
{
	if (!snd || !snd->wavetable) {
		/* Empty slot: no wavetable means no audio data. Skip silently.
		 * The catalog row still exists for reference parity. */
		return 0;
	}

	/* Resolve wavetable. wavetable is stored as offset within ctl. */
	u32 wt_off = s_offsetFromPointer(snd->wavetable);
	if (wt_off + sizeof(ALWaveTable) > ctl_size) {
		LOUD_FAILF_RT(channel,
			"sfx_idx=%d wavetable offset 0x%x + sizeof past ctl size 0x%x",
			sfx_idx, (unsigned)wt_off, (unsigned)ctl_size);
		return -1;
	}
	const ALWaveTable *wt = (const ALWaveTable *)(ctl_data + wt_off);

	/* Resolve sample byte range in the sfxtbl segment. */
	u32 sample_off = s_offsetFromPointer(wt->base);
	u32 sample_len = (u32)wt->len;
	if (sample_len == 0) {
		/* Wavetable with zero byte length = empty placeholder; skip. */
		return 0;
	}
	if (sample_off + sample_len > tbl_size) {
		LOUD_FAILF_RT(channel,
			"sfx_idx=%d sample range 0x%x..0x%x past tbl size 0x%x",
			sfx_idx, (unsigned)sample_off,
			(unsigned)(sample_off + sample_len), (unsigned)tbl_size);
		return -1;
	}

	/* Loop info -- ADPCM and RAW16 differ in struct, but the
	 * (start, end, count) sample-frame triple is shared in the JSON
	 * envelope. */
	s32 has_loop = 0;
	u32 loop_start = 0, loop_end = 0, loop_count = 0;
	/* ADPCM loop predictor restart vector (ALADPCMloop::state, ADPCM_STATE
	 * = short[16]). Consumed by the runtime at n_load.c for click-free loop
	 * seams; already byte-swapped into host order by the ctl preprocess
	 * (segaudio.c convertAudioAdpcmLoop). Only emitted for ALADPCM loops. */
	s32 has_loop_state = 0;
	const short *loop_state = NULL;
	if (wt->type == AL_ADPCM_WAVE) {
		u32 loop_off = s_offsetFromPointer(wt->waveInfo.adpcmWave.loop);
		if (loop_off != 0 && loop_off + sizeof(ALADPCMloop) <= ctl_size) {
			const ALADPCMloop *lp =
				(const ALADPCMloop *)(ctl_data + loop_off);
			loop_start = lp->start;
			loop_end   = lp->end;
			loop_count = lp->count;
			loop_state = lp->state;
			has_loop_state = 1;
			has_loop = 1;
		}
	} else if (wt->type == AL_RAW16_WAVE) {
		u32 loop_off = s_offsetFromPointer(wt->waveInfo.rawWave.loop);
		if (loop_off != 0 && loop_off + sizeof(ALRawLoop) <= ctl_size) {
			const ALRawLoop *lp =
				(const ALRawLoop *)(ctl_data + loop_off);
			loop_start = lp->start;
			loop_end   = lp->end;
			loop_count = lp->count;
			has_loop = 1;
		}
	}

	/* Catalog ID + filename slug. */
	char catalog_id[128];
	if (catalog_id_override && catalog_id_override[0]) {
		snprintf(catalog_id, sizeof(catalog_id), "%s", catalog_id_override);
	} else {
		(void)s_buildSfxCatalogId(sfx_idx, mode, catalog_id, sizeof(catalog_id));
	}

	char filename_slug[128];
	s_filenameSlug(catalog_id, filename_slug, sizeof(filename_slug));

	const char *kind_ext = (mode == PDAUDIO_WALK_VOICE) ? "pdvoice" : "pdsfx";
	char dst_rel[FS_MAXPATH];
	snprintf(dst_rel, sizeof(dst_rel),
		"%s/%s.%s", out_dir, filename_slug, kind_ext);

	const char *descriptor_name =
		(mode == PDAUDIO_WALK_VOICE) ? "voice.ini" : "sound.ini";
	if (!force_rewrite && fsFileSize(dst_rel) > 0 &&
	    s_existingArchiveHasEntry(dst_rel, descriptor_name) &&
	    s_existingArchiveHasEntry(dst_rel, "_meta/manifest.json") &&
	    s_existingArchiveHasEntry(dst_rel, "sample.wav") &&
	    s_existingArchiveEntryContains(dst_rel, "_meta/manifest.json",
			"\"key_base\"") &&
	    s_existingArchiveEntryContains(dst_rel, "_meta/manifest.json",
			"\"attack_time_us\"") &&
	    s_existingArchiveEntryContains(dst_rel, "_meta/manifest.json",
			"\"velocity_max\"")) return 0;

	u8 *wav_data = NULL;
	u32 wav_size = 0;
	u32 decoded_sample_count = 0;
	if (!s_buildWavPayload(ctl_data, ctl_size, wt,
	                       tbl_data + sample_off, sample_len,
	                       sample_rate, &wav_data, &wav_size,
	                       &decoded_sample_count)) {
		LOUD_FAILF_RT(channel,
			"sfx_idx=%d could not decode %s sample to WAV",
			sfx_idx, s_waveFormatString(wt->type));
		return -1;
	}

	/* Build _meta/manifest.json. Voice variant adds actor + transcript +
	 * language + context placeholder fields per Section 2.8 (curation
	 * fills them in a follow-up; "unknown" is the schema-stable
	 * sentinel). */
	const char *pd_kind = (mode == PDAUDIO_WALK_VOICE) ? "voice" : "sfx";
	const char *fmt_str = s_waveFormatString(wt->type);
	const char *sym = loaderEnumNameForSfxEnum(sfx_idx);
	const char *source_symbol = (source_symbol_override && source_symbol_override[0])
		? source_symbol_override : (sym ? sym : "");
	const char *archive_format = "WAV_PCM16";
	const ALKeyMap *keymap = NULL;
	u32 keymap_off = s_offsetFromPointer(snd->keyMap);
	if (keymap_off != 0 && keymap_off + sizeof(ALKeyMap) <= ctl_size) {
		keymap = (const ALKeyMap *)(ctl_data + keymap_off);
	}
	u8 key_min = keymap ? keymap->keyMin : 0;
	u8 key_max = keymap ? keymap->keyMax : 127;
	u8 key_base = keymap ? keymap->keyBase : 60;
	s8 key_detune = keymap ? keymap->detune : 0;
	u8 velocity_min = keymap ? keymap->velocityMin : 0;
	u8 velocity_max = keymap ? keymap->velocityMax : 0;

	const ALEnvelope *envelope = NULL;
	u32 envelope_off = s_offsetFromPointer(snd->envelope);
	if (envelope_off != 0 && envelope_off + sizeof(ALEnvelope) <= ctl_size) {
		envelope = (const ALEnvelope *)(ctl_data + envelope_off);
	}
	u32 attack_time_us = envelope ? envelope->attackTime : 0;
	u32 decay_time_us = envelope ? envelope->decayTime : 0;
	u32 release_time_us = envelope ? envelope->releaseTime : 0;
	u8 attack_volume = envelope ? envelope->attackVolume : 127;
	u8 decay_volume = envelope ? envelope->decayVolume : 127;
	s32 has_envelope = envelope != NULL;

	/* Build the optional ADPCM loop_state line (16 signed int16). Empty for
	 * non-ALADPCM or non-looping sounds; otherwise a full manifest line
	 * self-terminated with ",\n" so it slots after the has_loop field. */
	char loop_state_json[256];
	loop_state_json[0] = '\0';
	if (has_loop_state && loop_state) {
		size_t pos = 0;
		int n = snprintf(loop_state_json, sizeof(loop_state_json),
			"  \"loop_state\": [");
		if (n > 0) pos = (size_t)n;
		for (s32 i = 0; i < ADPCMFSIZE && pos < sizeof(loop_state_json); i++) {
			n = snprintf(loop_state_json + pos, sizeof(loop_state_json) - pos,
				"%d%s", (int)loop_state[i],
				i + 1 == ADPCMFSIZE ? "" : ", ");
			if (n <= 0) break;
			pos += (size_t)n;
		}
		if (pos < sizeof(loop_state_json)) {
			snprintf(loop_state_json + pos, sizeof(loop_state_json) - pos,
				"],\n");
		}
	}

	char manifest_buf[3072];
	int manifest_len;
	if (mode == PDAUDIO_WALK_VOICE) {
		manifest_len = snprintf(manifest_buf, sizeof(manifest_buf),
			"{\n"
			"  \"pd_kind\": \"%s\",\n"
			"  \"pd_schema_version\": 1,\n"
			"  \"id\": \"%s\",\n"
			"  \"format\": \"%s\",\n"
			"  \"source_format\": \"%s\",\n"
			"  \"sample_rate_hz\": %d,\n"
			"  \"data\": \"sample.wav\",\n"
			"  \"data_size\": %u,\n"
			"  \"source_data_size\": %u,\n"
			"  \"decoded_sample_count\": %u,\n"
			"  \"actor\": \"unknown\",\n"
			"  \"transcript\": \"\",\n"
			"  \"language\": \"\",\n"
			"  \"context\": \"\",\n"
			"  \"loop_start_samples\": %u,\n"
			"  \"loop_end_samples\": %u,\n"
			"  \"loop_count\": %u,\n"
			"  \"has_loop\": %s,\n"
			"%s"
			"  \"sample_pan\": %u,\n"
			"  \"sample_volume\": %u,\n"
			"  \"sound_flags\": %u,\n"
			"  \"source_index\": %d,\n"
			"  \"source_offset\": %u,\n"
			"  \"key_min\": %u,\n"
			"  \"key_max\": %u,\n"
			"  \"key_base\": %u,\n"
			"  \"key_detune\": %d,\n"
			"  \"velocity_min\": %u,\n"
			"  \"velocity_max\": %u,\n"
			"  \"has_envelope\": %s,\n"
			"  \"attack_time_us\": %u,\n"
			"  \"decay_time_us\": %u,\n"
			"  \"release_time_us\": %u,\n"
			"  \"attack_volume\": %u,\n"
			"  \"decay_volume\": %u,\n"
			"  \"source_symbol\": \"%s\"\n"
			"}\n",
			pd_kind, catalog_id, archive_format, fmt_str,
			sample_rate,
			(unsigned)wav_size,
			(unsigned)sample_len,
			(unsigned)decoded_sample_count,
			(unsigned)loop_start, (unsigned)loop_end, (unsigned)loop_count,
			has_loop ? "true" : "false",
			loop_state_json,
			(unsigned)snd->samplePan,
			(unsigned)snd->sampleVolume,
			(unsigned)snd->flags,
			sfx_idx,
			(unsigned)sample_off,
			(unsigned)key_min,
			(unsigned)key_max,
			(unsigned)key_base,
			(int)key_detune,
			(unsigned)velocity_min,
			(unsigned)velocity_max,
			has_envelope ? "true" : "false",
			(unsigned)attack_time_us,
			(unsigned)decay_time_us,
			(unsigned)release_time_us,
			(unsigned)attack_volume,
			(unsigned)decay_volume,
			source_symbol);
	} else {
		manifest_len = snprintf(manifest_buf, sizeof(manifest_buf),
			"{\n"
			"  \"pd_kind\": \"%s\",\n"
			"  \"pd_schema_version\": 1,\n"
			"  \"id\": \"%s\",\n"
			"  \"format\": \"%s\",\n"
			"  \"source_format\": \"%s\",\n"
			"  \"sample_rate_hz\": %d,\n"
			"  \"data\": \"sample.wav\",\n"
			"  \"data_size\": %u,\n"
			"  \"source_data_size\": %u,\n"
			"  \"decoded_sample_count\": %u,\n"
			"  \"loop_start_samples\": %u,\n"
			"  \"loop_end_samples\": %u,\n"
			"  \"loop_count\": %u,\n"
			"  \"has_loop\": %s,\n"
			"%s"
			"  \"sample_pan\": %u,\n"
			"  \"sample_volume\": %u,\n"
			"  \"sound_flags\": %u,\n"
			"  \"source_index\": %d,\n"
			"  \"source_offset\": %u,\n"
			"  \"key_min\": %u,\n"
			"  \"key_max\": %u,\n"
			"  \"key_base\": %u,\n"
			"  \"key_detune\": %d,\n"
			"  \"velocity_min\": %u,\n"
			"  \"velocity_max\": %u,\n"
			"  \"has_envelope\": %s,\n"
			"  \"attack_time_us\": %u,\n"
			"  \"decay_time_us\": %u,\n"
			"  \"release_time_us\": %u,\n"
			"  \"attack_volume\": %u,\n"
			"  \"decay_volume\": %u,\n"
			"  \"source_symbol\": \"%s\"\n"
			"}\n",
			pd_kind, catalog_id, archive_format, fmt_str,
			sample_rate,
			(unsigned)wav_size,
			(unsigned)sample_len,
			(unsigned)decoded_sample_count,
			(unsigned)loop_start, (unsigned)loop_end, (unsigned)loop_count,
			has_loop ? "true" : "false",
			loop_state_json,
			(unsigned)snd->samplePan,
			(unsigned)snd->sampleVolume,
			(unsigned)snd->flags,
			sfx_idx,
			(unsigned)sample_off,
			(unsigned)key_min,
			(unsigned)key_max,
			(unsigned)key_base,
			(int)key_detune,
			(unsigned)velocity_min,
			(unsigned)velocity_max,
			has_envelope ? "true" : "false",
			(unsigned)attack_time_us,
			(unsigned)decay_time_us,
			(unsigned)release_time_us,
			(unsigned)attack_volume,
			(unsigned)decay_volume,
			source_symbol);
	}
	if (manifest_len <= 0 || (size_t)manifest_len >= sizeof(manifest_buf)) {
		LOUD_FAILF_RT(channel,
			"manifest.json snprintf truncated for sfx_idx=%d", sfx_idx);
		free(wav_data);
		return -1;
	}

	char ini_buf[3072];
	int ini_len = snprintf(ini_buf, sizeof(ini_buf),
		"[%s]\n"
		"catalog_id = %s\n"
		"format = %s\n"
		"source_format = %s\n"
		"sample_rate_hz = %d\n"
		"file_path = sample.wav\n"
		"data_size = %u\n"
		"source_data_size = %u\n"
		"decoded_sample_count = %u\n"
		"loop_start_samples = %u\n"
		"loop_end_samples = %u\n"
		"loop_count = %u\n"
		"has_loop = %s\n"
		"sample_pan = %u\n"
		"sample_volume = %u\n"
		"key_min = %u\n"
		"key_max = %u\n"
		"key_base = %u\n"
		"key_detune = %d\n"
		"velocity_min = %u\n"
		"velocity_max = %u\n"
		"has_envelope = %s\n"
		"attack_time_us = %u\n"
		"decay_time_us = %u\n"
		"release_time_us = %u\n"
		"attack_volume = %u\n"
		"decay_volume = %u\n"
		"sound_flags = %u\n"
		"source_index = %d\n"
		"source_offset = %u\n"
		"source_symbol = %s\n",
		pd_kind, catalog_id, archive_format, fmt_str, sample_rate,
		(unsigned)wav_size,
		(unsigned)sample_len,
		(unsigned)decoded_sample_count,
		(unsigned)loop_start, (unsigned)loop_end, (unsigned)loop_count,
		has_loop ? "true" : "false",
		(unsigned)snd->samplePan,
		(unsigned)snd->sampleVolume,
		(unsigned)key_min,
		(unsigned)key_max,
		(unsigned)key_base,
		(int)key_detune,
		(unsigned)velocity_min,
		(unsigned)velocity_max,
		has_envelope ? "true" : "false",
		(unsigned)attack_time_us,
		(unsigned)decay_time_us,
		(unsigned)release_time_us,
		(unsigned)attack_volume,
		(unsigned)decay_volume,
		(unsigned)snd->flags,
		sfx_idx,
		(unsigned)sample_off,
		source_symbol);
	if (mode == PDAUDIO_WALK_VOICE) {
		ini_len += snprintf(ini_buf + ini_len, sizeof(ini_buf) - ini_len,
			"actor = unknown\n"
			"transcript = \n"
			"language = \n"
			"context = \n");
	}
	if (ini_len <= 0 || (size_t)ini_len >= sizeof(ini_buf)) {
		LOUD_FAILF_RT(channel,
			"%s snprintf truncated for sfx_idx=%d",
			descriptor_name, sfx_idx);
		free(wav_data);
		return -1;
	}

	char dst_full_buf[FS_MAXPATH + 1];
	const char *dst_full = fsFullPath(dst_rel, dst_full_buf, sizeof(dst_full_buf));
	if (!dst_full || !dst_full[0]) {
		LOUD_FAILF_RT(channel, "fsFullPath empty for \"%s\"", dst_rel);
		free(wav_data);
		return -1;
	}

	mod_archive_writer_t *aw = modArchiveBegin(dst_full);
	if (!aw) {
		LOUD_FAILF_RT(channel, "modArchiveBegin failed for \"%s\"", dst_full);
		free(wav_data);
		return -1;
	}

	asset_archive_writer_t asset_writer;
	if (assetArchiveWriterInit(&asset_writer, aw, pd_kind, catalog_id) !=
			MODARCHIVE_OK) {
		LOUD_FAILF_RT(channel,
			"assetArchiveWriterInit failed for \"%s\"", dst_full);
		modArchiveAbort(aw);
		free(wav_data);
		return -1;
	}
	assetArchiveWriterSetProvenance(&asset_writer,
		(mode == PDAUDIO_WALK_VOICE) ? "romextract_pdvoice" : "romextract_pdsfx",
		"sfxctl/sfxtbl", sfx_idx, source_symbol);

	if (assetArchiveWriterAddDescriptor(&asset_writer, descriptor_name,
			ini_buf, (u32)ini_len) != MODARCHIVE_OK) {
		LOUD_FAILF_RT(channel,
			"AddFileMem %s failed for \"%s\"", descriptor_name, dst_full);
		modArchiveAbort(aw);
		free(wav_data);
		return -1;
	}
	if (assetArchiveWriterAddManifestJson(&asset_writer,
			manifest_buf, (u32)manifest_len) != MODARCHIVE_OK) {
		LOUD_FAILF_RT(channel,
			"AddFileMem _meta/manifest.json failed for \"%s\"", dst_full);
		modArchiveAbort(aw);
		free(wav_data);
		return -1;
	}

	if (assetArchiveWriterAddPublicMem(&asset_writer, "sample.wav",
			(const char *)wav_data, wav_size, "sample") != MODARCHIVE_OK) {
		LOUD_FAILF_RT(channel,
			"AddFileMem sample.wav failed for \"%s\" (sfx_idx=%d len=%u)",
			dst_full, sfx_idx, (unsigned)wav_size);
		modArchiveAbort(aw);
		free(wav_data);
		return -1;
	}

	if (assetArchiveWriterFinishMetadata(&asset_writer) != MODARCHIVE_OK) {
		LOUD_FAILF_RT(channel,
			"assetArchiveWriterFinishMetadata failed for \"%s\"",
			dst_full);
		modArchiveAbort(aw);
		free(wav_data);
		return -1;
	}

	if (modArchiveFinish(aw) != 0) {
		LOUD_FAILF_RT(channel, "modArchiveFinish failed for \"%s\"", dst_full);
		free(wav_data);
		return -1;
	}

	free(wav_data);
	return 1;
}

static s32 s_emitOneMp3VoiceAlias(s32 confignum, union soundnumhack mapped,
                                  const char *out_dir, s32 force_rewrite,
                                  const char *channel, const char *alias_sym)
{
	union soundnumhack ref;
	ref.packed = 0;
	ref.hasconfig = 1;
	ref.confignum = (u16)confignum;
	s32 packed = (s32)(u16)ref.packed;

	char catalog_id[128];
	catalogReadableSoundRefId(packed, catalog_id, sizeof(catalog_id));

	char filename_slug[128];
	s_filenameSlug(catalog_id, filename_slug, sizeof(filename_slug));

	char dst_rel[FS_MAXPATH];
	snprintf(dst_rel, sizeof(dst_rel), "%s/%s.pdvoice",
		out_dir, filename_slug);

	if (!force_rewrite && fsFileSize(dst_rel) > 0 &&
			s_existingArchiveHasEntry(dst_rel, "voice.ini") &&
			s_existingArchiveHasEntry(dst_rel, "_meta/manifest.json") &&
			s_existingArchiveHasEntry(dst_rel, "sample.mp3") &&
			s_existingArchiveEntryContains(dst_rel, "_meta/manifest.json",
				"\"source_filenum\"")) {
		return 0;
	}

	char mp3_rel[FS_MAXPATH + 1];
	if (romExtractRelPathForFilenum((s32)mapped.id, mp3_rel,
			(s32)sizeof(mp3_rel)) <= 0) {
		LOUD_FAILF_RT(channel,
			"configured alias %s maps to MP3 file %d but no extracted "
			"source path exists",
			alias_sym ? alias_sym : "(unknown)", (s32)mapped.id);
		return -1;
	}

	u32 mp3_size = 0;
	void *mp3_bytes = fsFileLoad(mp3_rel, &mp3_size);
	if (!mp3_bytes || mp3_size == 0) {
		if (mp3_bytes) {
			sysMemFree(mp3_bytes);
		}
		LOUD_FAILF_RT(channel,
			"configured alias %s maps to MP3 file %d but source \"%s\" "
			"is missing or empty",
			alias_sym ? alias_sym : "(unknown)", (s32)mapped.id, mp3_rel);
		return -1;
	}

	const char *file_sym = loaderEnumNameForFileEnum((s32)mapped.id);
	char manifest_buf[2048];
	int manifest_len = snprintf(manifest_buf, sizeof(manifest_buf),
		"{\n"
		"  \"pd_kind\": \"voice\",\n"
		"  \"pd_schema_version\": 1,\n"
		"  \"id\": \"%s\",\n"
		"  \"format\": \"MP3\",\n"
		"  \"source_format\": \"MP3\",\n"
		"  \"data\": \"sample.mp3\",\n"
		"  \"data_size\": %u,\n"
		"  \"source_filenum\": %d,\n"
		"  \"source_index\": %d,\n"
		"  \"mapped_soundnum\": %d,\n"
		"  \"mp3_priority\": %u,\n"
		"  \"actor\": \"unknown\",\n"
		"  \"transcript\": \"\",\n"
		"  \"language\": \"\",\n"
		"  \"context\": \"\",\n"
		"  \"source_symbol\": \"%s\",\n"
		"  \"source_file_symbol\": \"%s\"\n"
		"}\n",
		catalog_id,
		(unsigned)mp3_size,
		(s32)mapped.id,
		packed,
		(s32)(u16)mapped.packed,
		(unsigned)mapped.mp3priority,
		alias_sym ? alias_sym : "",
		file_sym ? file_sym : "");
	if (manifest_len <= 0 || (size_t)manifest_len >= sizeof(manifest_buf)) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel,
			"manifest.json snprintf truncated for MP3 alias %s",
			alias_sym ? alias_sym : "(unknown)");
		return -1;
	}

	char ini_buf[2048];
	int ini_len = snprintf(ini_buf, sizeof(ini_buf),
		"[voice]\n"
		"catalog_id = %s\n"
		"format = MP3\n"
		"source_format = MP3\n"
		"file_path = sample.mp3\n"
		"data_size = %u\n"
		"source_index = %d\n"
		"mapped_soundnum = %d\n"
		"mp3_priority = %u\n"
		"source_symbol = %s\n"
		"source_file_symbol = %s\n"
		"actor = unknown\n"
		"transcript = \n"
		"language = \n"
		"context = \n",
		catalog_id,
		(unsigned)mp3_size,
		packed,
		(s32)(u16)mapped.packed,
		(unsigned)mapped.mp3priority,
		alias_sym ? alias_sym : "",
		file_sym ? file_sym : "");
	if (ini_len <= 0 || (size_t)ini_len >= sizeof(ini_buf)) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel,
			"voice.ini snprintf truncated for MP3 alias %s",
			alias_sym ? alias_sym : "(unknown)");
		return -1;
	}

	char dst_full_buf[FS_MAXPATH + 1];
	const char *dst_full = fsFullPath(dst_rel, dst_full_buf, sizeof(dst_full_buf));
	if (!dst_full || !dst_full[0]) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel, "fsFullPath empty for \"%s\"", dst_rel);
		return -1;
	}

	mod_archive_writer_t *aw = modArchiveBegin(dst_full);
	if (!aw) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel, "modArchiveBegin failed for \"%s\"", dst_full);
		return -1;
	}

	asset_archive_writer_t asset_writer;
	if (assetArchiveWriterInit(&asset_writer, aw, "voice", catalog_id) !=
			MODARCHIVE_OK) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel,
			"assetArchiveWriterInit failed for \"%s\"", dst_full);
		modArchiveAbort(aw);
		return -1;
	}
	assetArchiveWriterSetProvenance(&asset_writer,
		"romextract_pdvoice", mp3_rel, (s32)mapped.id,
		alias_sym ? alias_sym : "");

	if (assetArchiveWriterAddDescriptor(&asset_writer, "voice.ini",
			ini_buf, (u32)ini_len) != MODARCHIVE_OK ||
			assetArchiveWriterAddManifestJson(&asset_writer,
				manifest_buf, (u32)manifest_len) != MODARCHIVE_OK ||
			assetArchiveWriterAddPublicMem(&asset_writer, "sample.mp3",
				(const char *)mp3_bytes, mp3_size, "sample") !=
				MODARCHIVE_OK ||
			assetArchiveWriterFinishMetadata(&asset_writer) !=
				MODARCHIVE_OK) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel,
			"failed writing MP3 voice archive \"%s\"", dst_full);
		modArchiveAbort(aw);
		return -1;
	}

	if (modArchiveFinish(aw) != 0) {
		sysMemFree(mp3_bytes);
		LOUD_FAILF_RT(channel, "modArchiveFinish failed for \"%s\"", dst_full);
		return -1;
	}

	sysMemFree(mp3_bytes);
	return 1;
}

/* Engine Phase 4 fan-out context for the pdsfx / pdvoice bank walker.
 * Lives at file scope so the worker function (which can't be nested
 * inside the bank walker in standard C) can see the type. */
typedef struct {
	const u8           *ctl_data;
	u32                 ctl_size;
	const u8           *tbl_data;
	u32                 tbl_size;
	const ALInstrument *inst;
	s32                 sample_rate;
	pdaudio_walk_mode_t mode;
	const char         *out_dir;
	const char         *channel;
	s32                 force_rewrite;
	const u8           *voice_cache;
	s32                 want_voice;
	s32                 sound_count;
	SDL_atomic_t        written;
	SDL_atomic_t        skipped;
	SDL_atomic_t        failed;
	SDL_atomic_t        processed;
} pdsfx_fanout_ctx_t;

static void s_pdsfxWork(int i, void *user)
{
	pdsfx_fanout_ctx_t *c = (pdsfx_fanout_ctx_t *)user;
	if (i < 0 || i >= c->sound_count) return;

	s32 is_voice = c->voice_cache[i] ? 1 : 0;

	if (is_voice != c->want_voice) {
		SDL_AtomicAdd(&c->skipped, 1);
		goto progress;
	}

	u32 snd_off = (u32)(uintptr_t)c->inst->soundArray[i];
	if (snd_off + sizeof(ALSound) > c->ctl_size) {
		LOUD_FAILF_RT(c->channel,
			"sound[%d] offset 0x%x past ctl size 0x%x",
			i, (unsigned)snd_off, (unsigned)c->ctl_size);
		SDL_AtomicAdd(&c->failed, 1);
		goto progress;
	}
	const ALSound *snd = (const ALSound *)(c->ctl_data + snd_off);

	s32 r = s_emitOneSound(i, c->ctl_data, c->ctl_size,
	                        c->tbl_data, c->tbl_size,
	                        snd, c->sample_rate, c->mode,
	                        c->out_dir, c->force_rewrite, c->channel,
	                        NULL, NULL);
	if (r > 0)        SDL_AtomicAdd(&c->written, 1);
	else if (r == 0)  SDL_AtomicAdd(&c->skipped, 1);
	else              SDL_AtomicAdd(&c->failed,  1);

progress:
	{
		int done = SDL_AtomicAdd(&c->processed, 1) + 1;
		if ((done & 0x3f) == 0 || done == c->sound_count) {
			bootProgressUpdate(done, c->sound_count);
		}
	}
}

static void s_emitConfiguredAliasSounds(const pdsfx_fanout_ctx_t *c,
                                        s32 *written, s32 *skipped,
                                        s32 *failed)
{
	if (!c) return;

	s32 mp3_aliases = 0;
	for (s32 r = 0; r < g_NumAudioRussMappings; r++) {
		union soundnumhack ref;
		ref.packed = 0;
		ref.hasconfig = 1;
		ref.confignum = (u16)r;
		s32 packed = (s32)(u16)ref.packed;
		const char *alias_sym = loaderEnumNameForSfxEnum(packed);
		if (!alias_sym) {
			continue;
		}

		union soundnumhack mapped;
		mapped.packed = g_AudioRussMappings[r].soundnum;
		if (mapped.mp3priority != 0) {
			if (c->mode == PDAUDIO_WALK_VOICE) {
				s32 result = s_emitOneMp3VoiceAlias(r, mapped, c->out_dir,
					c->force_rewrite, c->channel, alias_sym);
				if (result > 0 && written) {
					(*written)++;
				} else if (result == 0 && skipped) {
					(*skipped)++;
				} else if (result < 0 && failed) {
					(*failed)++;
				}
				mp3_aliases++;
			} else {
				if (skipped) (*skipped)++;
			}
			continue;
		}

		if (c->mode != PDAUDIO_WALK_SFX) {
			continue;
		}

		s32 leaf = (s32)mapped.id;
		if (leaf < 0 || leaf >= c->sound_count) {
			if (failed) (*failed)++;
			LOUD_FAILF_RT(c->channel,
				"configured alias %s maps outside sound bank (leaf=%d)",
				alias_sym, leaf);
			continue;
		}

		u32 snd_off = (u32)(uintptr_t)c->inst->soundArray[leaf];
		if (snd_off + sizeof(ALSound) > c->ctl_size) {
			if (failed) (*failed)++;
			LOUD_FAILF_RT(c->channel,
				"configured alias %s sound[%d] offset 0x%x past ctl size 0x%x",
				alias_sym, leaf, (unsigned)snd_off, (unsigned)c->ctl_size);
			continue;
		}

		char alias_id[128];
		catalogReadableSoundRefId(packed, alias_id, sizeof(alias_id));
		const ALSound *snd = (const ALSound *)(c->ctl_data + snd_off);
		s32 result = s_emitOneSound(leaf, c->ctl_data, c->ctl_size,
			c->tbl_data, c->tbl_size, snd, c->sample_rate, PDAUDIO_WALK_SFX,
			c->out_dir, c->force_rewrite, c->channel, alias_id, alias_sym);
		if (result > 0 && written) {
			(*written)++;
		} else if (result == 0 && skipped) {
			(*skipped)++;
		} else if (result < 0 && failed) {
			(*failed)++;
		}
	}

	if (mp3_aliases > 0) {
		sysLogPrintf(LOG_NOTE,
			"romextract pdvoice: %d configured MP3 alias archive(s) checked",
			mp3_aliases);
	}
}

s32 romextract_pdaudio_walkBank(pdaudio_walk_mode_t mode, s32 force_rewrite)
{
	const char *channel = (mode == PDAUDIO_WALK_VOICE)
		? "EXTRACT.PDVOICE" : "EXTRACT.PDSFX";
	const char *out_subdir = (mode == PDAUDIO_WALK_VOICE)
		? PDSFX_OUT_DIR_VOICE : PDSFX_OUT_DIR_SFX;
	const char *kind_label = (mode == PDAUDIO_WALK_VOICE) ? "pdvoice" : "pdsfx";
	/* Fast-cache kind is bumped independently of the log label so a field
	 * change forces the directory stamp stale without polluting log output.
	 * _b943fields adds the additive ALADPCM "loop_state" predictor vector. */
	const char *cache_kind = (mode == PDAUDIO_WALK_VOICE)
		? "pdvoice_b943fields" : "pdsfx_b943fields";

	const u8 *ctl_data = NULL;
	u32 ctl_size = 0;
	const u8 *tbl_data = NULL;
	u32 tbl_size = 0;

	if (!s_findSegment("sfxctl", &ctl_data, &ctl_size)) {
		sysLogPrintf(LOG_NOTE,
			"romextract %s: \"sfxctl\" segment not loaded "
			"(server build or pre-romdata-init); skipping", kind_label);
		return 0;
	}
	if (!s_findSegment("sfxtbl", &tbl_data, &tbl_size)) {
		sysLogPrintf(LOG_NOTE,
			"romextract %s: \"sfxtbl\" segment not loaded; skipping",
			kind_label);
		return 0;
	}

	if (ctl_size < sizeof(ALBankFile)) {
		LOUD_FAILF_RT(channel,
			"sfxctl size %u smaller than ALBankFile header",
			(unsigned)ctl_size);
		return -1;
	}

	if (!fsDataDirEnsure()) {
		LOUD_FAILF_RT(channel, "fsDataDirEnsure failed");
		return -1;
	}

	char dataDirBuf[FS_MAXPATH + 1];
	const char *dataDir = fsDataDir(dataDirBuf, sizeof(dataDirBuf));

	/* B-320 (2026-05-03): create the parent audio/ dir before the leaf
	 * audio/sfx or audio/voice subdir. _mkdir does not create intermediate
	 * directories on Windows, so the leaf create silently failed with ENOENT
	 * pre-fix and every modArchiveBegin downstream blew up. */
	char audio_parent[FS_MAXPATH];
	snprintf(audio_parent, sizeof(audio_parent), "%s/audio", dataDir);
	if (!fsCreateDir(audio_parent)) {
		LOUD_FAILF_RT(channel, "fsCreateDir(\"%s\") failed", audio_parent);
		return -1;
	}

	char out_dir[FS_MAXPATH];
	snprintf(out_dir, sizeof(out_dir), "%s/%s", dataDir, out_subdir);
	if (!fsCreateDir(out_dir)) {
		LOUD_FAILF_RT(channel, "fsCreateDir(\"%s\") failed", out_dir);
		return -1;
	}

	/* Walk into bank[0] -> instArray[0]. The SFX bank stores all
	 * leaf sounds in a single instrument; PD's sndLoadSfxCtl confirms
	 * "the first (and only) bank" and "the first (and only) instrument"
	 * (src/lib/snd.c around line 970). */
	const ALBankFile *bf = (const ALBankFile *)ctl_data;
	if (bf->bankCount < 1) {
		LOUD_FAILF_RT(channel, "ALBankFile bankCount=%d (<1)",
			(int)bf->bankCount);
		return -1;
	}

	u32 bank_off = s_offsetFromPointer(bf->bankArray[0]);
	if (bank_off + sizeof(ALBank) > ctl_size) {
		LOUD_FAILF_RT(channel,
			"bank[0] offset 0x%x past ctl size 0x%x",
			(unsigned)bank_off, (unsigned)ctl_size);
		return -1;
	}
	const ALBank *bank = (const ALBank *)(ctl_data + bank_off);
	s32 sample_rate = bank->sampleRate > 0 ? bank->sampleRate : 22050;

	if (bank->instCount < 1) {
		LOUD_FAILF_RT(channel, "ALBank instCount=%d (<1)",
			(int)bank->instCount);
		return -1;
	}

	u32 inst_off = s_offsetFromPointer(bank->instArray[0]);
	if (inst_off + sizeof(ALInstrument) > ctl_size) {
		LOUD_FAILF_RT(channel,
			"inst[0] offset 0x%x past ctl size 0x%x",
			(unsigned)inst_off, (unsigned)ctl_size);
		return -1;
	}
	const ALInstrument *inst = (const ALInstrument *)(ctl_data + inst_off);

	s32 sound_count = inst->soundCount;
	if (sound_count <= 0) {
		LOUD_FAILF_RT(channel, "ALInstrument soundCount=%d (<=0)",
			sound_count);
		return -1;
	}

	/* Bound check: the soundArray follows ALInstrument inline, so
	 * verify enough room for sound_count uintptr_t entries beyond
	 * the base struct. ALInstrument's struct already declares
	 * soundArray[1] so we subtract one to avoid double-counting. */
	if (inst_off + sizeof(ALInstrument)
	    + (size_t)(sound_count - 1) * sizeof(uintptr_t)
	    > ctl_size) {
		LOUD_FAILF_RT(channel,
			"inst soundArray spans past ctl size (count=%d off=0x%x)",
			sound_count, (unsigned)inst_off);
		return -1;
	}

	{
		const char *ext = (mode == PDAUDIO_WALK_VOICE) ? ".pdvoice" : ".pdsfx";
		if (romExtractPdFastCacheCanSkip(cache_kind, out_dir,
				ext, force_rewrite) &&
				(mode != PDAUDIO_WALK_SFX ||
					s_configuredAliasArchivesComplete(out_dir)) &&
				(mode != PDAUDIO_WALK_VOICE ||
					s_configuredMp3VoiceArchivesComplete(out_dir))) {
			bootProgressUpdate(sound_count, sound_count);
			sysLogPrintf(LOG_NOTE,
				"romextract %s: written=0 skipped=%d failed=0 "
				"sound_count=%d sample_rate=%d (out=%s, fast-cache)",
				kind_label, sound_count, sound_count,
				sample_rate, out_dir);
			return 0;
		}
	}

	/* Voice bitset cache: 1 byte per leaf SFX index. We size on
	 * sound_count which the SFX bank reports; the russ table can never
	 * point past it. */
	u8 *voice_cache = sysMemZeroAlloc((u32)sound_count);
	if (!voice_cache) {
		LOUD_FAILF_RT(channel, "sysMemZeroAlloc(%d) failed for voice cache",
			sound_count);
		return -1;
	}
	s_buildVoiceCache(voice_cache, (u32)sound_count);

	/* Engine Phase 4: per-sound fan-out.  Each iteration is fully
	 * independent (separate ZIP file write to a unique slug); the
	 * shared inputs (ctl_data / tbl_data / inst / voice_cache) are
	 * read-only across workers.  Counters are atomic so no merge
	 * step is needed.  Manager thread participates inline via
	 * bootPoolForRangeBlocking. */
	pdsfx_fanout_ctx_t fxctx;
	memset(&fxctx, 0, sizeof(fxctx));
	fxctx.ctl_data      = ctl_data;
	fxctx.ctl_size      = ctl_size;
	fxctx.tbl_data      = tbl_data;
	fxctx.tbl_size      = tbl_size;
	fxctx.inst          = inst;
	fxctx.sample_rate   = sample_rate;
	fxctx.mode          = mode;
	fxctx.out_dir       = out_dir;
	fxctx.channel       = channel;
	/* In-place cache-kind bump (B-943): force a one-time per-file rewrite when
	 * the stored kind differs from the current one (no-op on clean install or
	 * unchanged kind). cache_kind varies by mode (voice/sfx). */
	fxctx.force_rewrite = force_rewrite |
		romExtractPdFastCacheKindMismatch(cache_kind, out_dir);
	fxctx.voice_cache   = voice_cache;
	fxctx.want_voice    = (mode == PDAUDIO_WALK_VOICE) ? 1 : 0;
	fxctx.sound_count   = sound_count;
	SDL_AtomicSet(&fxctx.written,   0);
	SDL_AtomicSet(&fxctx.skipped,   0);
	SDL_AtomicSet(&fxctx.failed,    0);
	SDL_AtomicSet(&fxctx.processed, 0);

	bootProgressUpdate(0, sound_count);
	bootPoolForRangeBlocking(0, sound_count, s_pdsfxWork, &fxctx);
	bootProgressUpdate(sound_count, sound_count);

	s32 written = SDL_AtomicGet(&fxctx.written);
	s32 skipped = SDL_AtomicGet(&fxctx.skipped);
	s32 failed  = SDL_AtomicGet(&fxctx.failed);

	s_emitConfiguredAliasSounds(&fxctx, &written, &skipped, &failed);

	sysMemFree(voice_cache);

	sysLogPrintf(LOG_NOTE,
		"romextract %s: written=%d skipped=%d failed=%d "
		"sound_count=%d sample_rate=%d (out=%s)",
		kind_label, written, skipped, failed, sound_count,
		sample_rate, out_dir);

	if (failed == 0) {
		const char *ext = (mode == PDAUDIO_WALK_VOICE) ? ".pdvoice" : ".pdsfx";
		romExtractPdFastCacheWrite(cache_kind, out_dir, ext);
	}

	return written;
}

s32 romExtractAllPdsfx(s32 force_rewrite)
{
	return romextract_pdaudio_walkBank(PDAUDIO_WALK_SFX, force_rewrite);
}

#else /* PD_SERVER */

s32 romextract_pdaudio_walkBank(pdaudio_walk_mode_t mode, s32 force_rewrite)
{
	(void)mode; (void)force_rewrite;
	return 0;
}

s32 romExtractAllPdsfx(s32 force_rewrite)
{
	(void)force_rewrite;
	return 0;
}

#endif /* PD_SERVER */
