/**
 * updater_gui.c -- Standalone PC update utility for Perfect Dark 2.
 *
 * Ships alongside PerfectDark.exe and PerfectDarkServer.exe as Updater.exe.
 * If a release breaks the main executables, end users can run Updater.exe
 * to download and install a fixed version from the GitHub Releases feed.
 *
 * Single-file Win32/WinAPI GUI -- no MFC, no WPF. libcurl statically
 * linked (same chain as PerfectDark.exe). SHA-256 via port/src/sha256.c.
 * CA bundle embedded via cacert_blob.h (generated by CMake).
 *
 * Worker threads run via _beginthreadex; results are posted back to the
 * UI thread with WM_APP_* messages. The UI thread owns all window state
 * and only reads completion payloads that the worker has finished writing.
 */

#include <windows.h>
#include <commctrl.h>
#include <shellapi.h>
#include <process.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include <curl/curl.h>

#include "sha256.h"
#include "versioninfo.h"
#include "cacert_blob.h"

/* versioninfo.h exposes VERSION_{MAJOR,MINOR,PATCH} as integer macros;
 * build the user-agent string locally so we do not pull in the rest of the
 * project's version utilities. */
#ifndef UPDATER_STRINGIFY
#define UPDATER_STRINGIFY_(x) #x
#define UPDATER_STRINGIFY(x)  UPDATER_STRINGIFY_(x)
#endif
#define UPDATER_VERSION_STRING \
	UPDATER_STRINGIFY(VERSION_MAJOR) "." \
	UPDATER_STRINGIFY(VERSION_MINOR) "." \
	UPDATER_STRINGIFY(VERSION_PATCH)

/* ========================================================================
 * Constants
 * ======================================================================== */

#define APP_TITLE            "Perfect Dark 2 -- Updater"
#define APP_WINDOW_CLASS     "PD2UpdaterWindow"
#define GITHUB_OWNER         "MikeHazeJr"
#define GITHUB_REPO          "perfect-dark-2"
#define ASSET_ZIP_SUFFIX     ".zip"
#define TAG_PREFIX           "v"
#define DEFAULT_PROTECTED    "mods,data,extracted,saves"

#define MAX_RELEASES         64
#define WINDOW_CLIENT_W      720  /* default + minimum client-area width */
#define WINDOW_CLIENT_H      620  /* default + minimum client-area height */
#define MAX_URL_LEN          512
#define MAX_TAG_LEN          64
#define MAX_NAME_LEN         128
#define MAX_BODY_LEN         4096

#define COL_BG               RGB(0x12, 0x14, 0x18)  /* dark background */
#define COL_BG_ALT           RGB(0x1C, 0x1E, 0x24)  /* slightly lighter card bg */
#define COL_TEXT             RGB(0xF0, 0xF0, 0xF0)
#define COL_TEXT_DIM         RGB(0xA0, 0xA8, 0xB0)
#define COL_ACCENT           RGB(0x00, 0x90, 0xD0)  /* PD2 blue */
#define COL_ACCENT_HOVER     RGB(0x24, 0xA8, 0xE0)
#define COL_ACCENT_PRESSED   RGB(0x00, 0x6E, 0xA0)
#define COL_DANGER           RGB(0xE0, 0x50, 0x50)
#define COL_SUCCESS          RGB(0x60, 0xC0, 0x70)

/* Control IDs */
enum {
	IDC_CURRENT_VERSION = 1001,
	IDC_SHOW_DEV_RELEASES,
	IDC_BTN_CHECK,
	IDC_LIST_RELEASES,
	IDC_RELEASE_NOTES,
	IDC_PROGRESS,
	IDC_STATUS,
	IDC_BTN_UPDATE,
	IDC_BTN_CLOSE,
	IDC_TITLE,
	IDC_LBL_RELEASES,
	IDC_LBL_NOTES,
};

/* Worker -> UI messages */
enum {
	WM_APP_CHECK_DONE      = WM_APP + 1,
	WM_APP_CHECK_FAILED    = WM_APP + 2,
	WM_APP_DOWNLOAD_BEGIN  = WM_APP + 3,
	WM_APP_DOWNLOAD_TICK   = WM_APP + 4,
	WM_APP_DOWNLOAD_DONE   = WM_APP + 5,
	WM_APP_DOWNLOAD_FAIL   = WM_APP + 6,
	WM_APP_APPLY_TICK      = WM_APP + 7,
	WM_APP_APPLY_DONE      = WM_APP + 8,
	WM_APP_APPLY_FAIL      = WM_APP + 9,
};

/* ========================================================================
 * Data types
 * ======================================================================== */

typedef struct {
	int  major;
	int  minor;
	int  patch;
} pdver_t;

typedef struct {
	pdver_t version;
	char    tag[MAX_TAG_LEN];
	char    name[MAX_NAME_LEN];
	char    body[MAX_BODY_LEN];
	char    assetUrl[MAX_URL_LEN];
	char    hashUrl[MAX_URL_LEN];
	long long assetSize;
	int     isPrerelease;
	int     isDraft;
} release_t;

/* Shared state — owned by the UI thread; worker threads read/write via
 * the critical section where noted. */
typedef struct {
	/* Window handles */
	HWND hMain;
	HWND hBtnCheck;
	HWND hBtnUpdate;
	HWND hBtnClose;
	HWND hList;
	HWND hNotes;
	HWND hProgress;
	HWND hStatus;
	HWND hCurrentVer;
	HWND hShowDevReleases;
	HWND hTitle;
	HWND hLblReleases;
	HWND hLblNotes;

	/* Theme */
	HFONT hFontUI;
	HFONT hFontTitle;
	HBRUSH hBrushBg;
	HBRUSH hBrushBgAlt;

	/* Settings */
	int showDevReleases;  /* 0 = stable only (default), 1 = stable + dev */
	pdver_t currentVersion;
	char versionStr[32];

	/* Paths */
	char exePath[MAX_PATH];
	char installDir[MAX_PATH];
	char settingsPath[MAX_PATH];
	char updateZipPath[MAX_PATH];
	char stagingDir[MAX_PATH];
	char selfOldPath[MAX_PATH];

	/* Releases (owned by UI thread; worker writes into scratch, then
	 * hands off via the completion message) */
	release_t allReleases[MAX_RELEASES]; /* full fetch — never re-filtered */
	int allReleaseCount;
	release_t releases[MAX_RELEASES];    /* view: filtered by showDevReleases */
	int releaseCount;
	int selectedIndex;

	/* Worker state (guarded by cs) */
	CRITICAL_SECTION cs;
	HANDLE hWorker;
	volatile LONG cancelFlag;
	volatile LONG workerBusy;

	/* Progress bytes shared from worker to UI (tick thread-safe via
	 * InterlockedExchange64) */
	volatile LONGLONG bytesDone;
	volatile LONGLONG bytesTotal;

	/* Final error message (copied before posting the fail message) */
	char errorMsg[512];

	/* Scratch buffer: worker populates this and UI copies to .releases[] on
	 * CHECK_DONE */
	release_t scratchReleases[MAX_RELEASES];
	int scratchCount;
} app_state_t;

static app_state_t g_App;

/* ========================================================================
 * Version helpers (mirror of port/src/updater.c)
 * ======================================================================== */

static int versionParseStr(const char *str, pdver_t *out)
{
	if (!str || !out) return -1;
	memset(out, 0, sizeof(*out));
	if (*str == 'v') str++;
	if (sscanf(str, "%d.%d.%d", &out->major, &out->minor, &out->patch) < 3) {
		return -1;
	}
	return 0;
}

static int versionParseTagStr(const char *tag, pdver_t *ver)
{
	if (!tag || !ver) return -1;
	if (tag[0] == 'v') {
		return versionParseStr(tag, ver);
	}
	const char *vp = strstr(tag, "-v");
	if (!vp) return -1;
	return versionParseStr(vp + 1, ver);
}

static int versionCmp(const pdver_t *a, const pdver_t *b)
{
	if (a->major != b->major) return a->major - b->major;
	if (a->minor != b->minor) return a->minor - b->minor;
	return a->patch - b->patch;
}

static void versionFmt(const pdver_t *v, char *buf, size_t n)
{
	snprintf(buf, n, "%d.%d.%d", v->major, v->minor, v->patch);
}

/* ========================================================================
 * Mini JSON tokenizer — same shape as port/src/updater.c so the API
 * response parser is identical.
 * ======================================================================== */

typedef enum {
	JTOK_NONE = 0, JTOK_LBRACE, JTOK_RBRACE, JTOK_LBRACKET, JTOK_RBRACKET,
	JTOK_COLON, JTOK_COMMA, JTOK_STRING, JTOK_NUMBER, JTOK_TRUE, JTOK_FALSE,
	JTOK_NULL, JTOK_EOF, JTOK_ERROR,
} jtok_type_t;

typedef struct {
	const char *start;
	int len;
	jtok_type_t type;
} jtok_t;

typedef struct {
	const char *pos;
	jtok_t cur;
} jparse_t;

static void jp_skipws(jparse_t *p)
{
	while (*p->pos && (*p->pos == ' ' || *p->pos == '\t' || *p->pos == '\n' || *p->pos == '\r')) {
		p->pos++;
	}
}

static jtok_t jp_next(jparse_t *p)
{
	jtok_t tok = { NULL, 0, JTOK_NONE };
	jp_skipws(p);

	if (!*p->pos) { tok.type = JTOK_EOF; return tok; }

	tok.start = p->pos;

	switch (*p->pos) {
	case '{': tok.type = JTOK_LBRACE; tok.len = 1; p->pos++; break;
	case '}': tok.type = JTOK_RBRACE; tok.len = 1; p->pos++; break;
	case '[': tok.type = JTOK_LBRACKET; tok.len = 1; p->pos++; break;
	case ']': tok.type = JTOK_RBRACKET; tok.len = 1; p->pos++; break;
	case ':': tok.type = JTOK_COLON; tok.len = 1; p->pos++; break;
	case ',': tok.type = JTOK_COMMA; tok.len = 1; p->pos++; break;
	case '"': {
		p->pos++;
		tok.start = p->pos;
		while (*p->pos && *p->pos != '"') {
			if (*p->pos == '\\') p->pos++;
			if (*p->pos) p->pos++;
		}
		tok.len = (int)(p->pos - tok.start);
		tok.type = JTOK_STRING;
		if (*p->pos == '"') p->pos++;
		break;
	}
	case 't':
		if (strncmp(p->pos, "true", 4) == 0) {
			tok.type = JTOK_TRUE; tok.len = 4; p->pos += 4;
		} else {
			tok.type = JTOK_ERROR; tok.len = 1; p->pos++;
		}
		break;
	case 'f':
		if (strncmp(p->pos, "false", 5) == 0) {
			tok.type = JTOK_FALSE; tok.len = 5; p->pos += 5;
		} else {
			tok.type = JTOK_ERROR; tok.len = 1; p->pos++;
		}
		break;
	case 'n':
		if (strncmp(p->pos, "null", 4) == 0) {
			tok.type = JTOK_NULL; tok.len = 4; p->pos += 4;
		} else {
			tok.type = JTOK_ERROR; tok.len = 1; p->pos++;
		}
		break;
	default:
		if (*p->pos == '-' || (*p->pos >= '0' && *p->pos <= '9')) {
			tok.type = JTOK_NUMBER;
			if (*p->pos == '-') p->pos++;
			while (*p->pos >= '0' && *p->pos <= '9') p->pos++;
			if (*p->pos == '.') {
				p->pos++;
				while (*p->pos >= '0' && *p->pos <= '9') p->pos++;
			}
			tok.len = (int)(p->pos - tok.start);
		} else {
			tok.type = JTOK_ERROR; tok.len = 1; p->pos++;
		}
		break;
	}

	p->cur = tok;
	return tok;
}

static int jp_iskey(const jtok_t *tok, const char *key)
{
	if (tok->type != JTOK_STRING) return 0;
	int klen = (int)strlen(key);
	return (tok->len == klen && strncmp(tok->start, key, klen) == 0);
}

static void jp_copystr(const jtok_t *tok, char *buf, int bufsize)
{
	int len = tok->len;
	if (len >= bufsize) len = bufsize - 1;
	if (len > 0) memcpy(buf, tok->start, len);
	buf[len] = '\0';
}

static void jp_copystr_unescape(const jtok_t *tok, char *buf, int bufsize)
{
	const char *src = tok->start;
	int srclen = tok->len;
	int di = 0;
	for (int si = 0; si < srclen && di < bufsize - 1; si++) {
		if (src[si] == '\\' && si + 1 < srclen) {
			si++;
			switch (src[si]) {
			case 'n':  buf[di++] = '\n'; break;
			case 'r':  buf[di++] = '\r'; break;
			case 't':  buf[di++] = '\t'; break;
			case '"':  buf[di++] = '"';  break;
			case '\\': buf[di++] = '\\'; break;
			case '/':  buf[di++] = '/';  break;
			default:   buf[di++] = src[si]; break;
			}
		} else {
			buf[di++] = src[si];
		}
	}
	buf[di] = '\0';
}

static void jp_skipval(jparse_t *p)
{
	jtok_t tok = jp_next(p);
	if (tok.type == JTOK_LBRACE) {
		int depth = 1;
		while (depth > 0) {
			tok = jp_next(p);
			if (tok.type == JTOK_LBRACE) depth++;
			else if (tok.type == JTOK_RBRACE) depth--;
			else if (tok.type == JTOK_EOF) return;
		}
	} else if (tok.type == JTOK_LBRACKET) {
		int depth = 1;
		while (depth > 0) {
			tok = jp_next(p);
			if (tok.type == JTOK_LBRACKET) depth++;
			else if (tok.type == JTOK_RBRACKET) depth--;
			else if (tok.type == JTOK_EOF) return;
		}
	}
}

/* ========================================================================
 * libcurl buffer callbacks
 * ======================================================================== */

typedef struct {
	char *data;
	size_t size;
	size_t capacity;
} curl_buffer_t;

static size_t curlMemWrite(void *contents, size_t size, size_t nmemb, void *userp)
{
	curl_buffer_t *buf = (curl_buffer_t *)userp;
	size_t total = size * nmemb;
	if (buf->size + total >= buf->capacity) {
		size_t newcap = (buf->capacity == 0) ? 4096 : buf->capacity;
		while (newcap <= buf->size + total) newcap *= 2;
		char *newdata = (char *)realloc(buf->data, newcap);
		if (!newdata) return 0;
		buf->data = newdata;
		buf->capacity = newcap;
	}
	memcpy(buf->data + buf->size, contents, total);
	buf->size += total;
	buf->data[buf->size] = '\0';
	return total;
}

typedef struct {
	FILE *fp;
	LONGLONG written;
} curl_file_ctx_t;

static size_t curlFileWrite(void *contents, size_t size, size_t nmemb, void *userp)
{
	curl_file_ctx_t *ctx = (curl_file_ctx_t *)userp;
	if (InterlockedCompareExchange(&g_App.cancelFlag, 0, 0)) return 0;
	size_t total = size * nmemb;
	size_t written = fwrite(contents, 1, total, ctx->fp);
	ctx->written += (LONGLONG)written;
	InterlockedExchange64(&g_App.bytesDone, ctx->written);
	PostMessage(g_App.hMain, WM_APP_DOWNLOAD_TICK, 0, 0);
	return written;
}

static int curlXfer(void *clientp, curl_off_t dltotal, curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
{
	(void)clientp; (void)ultotal; (void)ulnow; (void)dlnow;
	if (dltotal > 0) InterlockedExchange64(&g_App.bytesTotal, (LONGLONG)dltotal);
	if (InterlockedCompareExchange(&g_App.cancelFlag, 0, 0)) return 1;
	return 0;
}

static void curlSetupTLS(CURL *curl)
{
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);

	if (cacert_pem_size > 0) {
		struct curl_blob blob;
		blob.data = (void *)cacert_pem_data;
		blob.len  = cacert_pem_size;
		blob.flags = CURL_BLOB_COPY;
		curl_easy_setopt(curl, CURLOPT_CAINFO_BLOB, &blob);
	}

#if defined(CURLSSLOPT_NATIVE_CA)
	curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, (long)CURLSSLOPT_NATIVE_CA);
#endif
}

static CURLcode curlGet(const char *url, curl_buffer_t *buf, long *httpCodeOut)
{
	CURL *curl = curl_easy_init();
	if (!curl) {
		if (httpCodeOut) *httpCodeOut = 0;
		return CURLE_FAILED_INIT;
	}

	memset(buf, 0, sizeof(*buf));

	curl_easy_setopt(curl, CURLOPT_URL, url);
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curlMemWrite);
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, buf);
	curl_easy_setopt(curl, CURLOPT_USERAGENT, "PerfectDark-Updater/" UPDATER_VERSION_STRING);
	curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);
	curlSetupTLS(curl);
	curl_easy_setopt(curl, CURLOPT_HTTPGET, 1L);

	struct curl_slist *headers = NULL;
	headers = curl_slist_append(headers, "Accept: application/vnd.github+json");
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

	CURLcode res = curl_easy_perform(curl);

	long httpCode = 0;
	if (res == CURLE_OK) {
		curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &httpCode);
	}
	if (httpCodeOut) *httpCodeOut = httpCode;

	curl_slist_free_all(headers);
	curl_easy_cleanup(curl);
	return res;
}

/* ========================================================================
 * Release parser
 * ======================================================================== */

static int str_ends_with(const char *str, const char *suffix)
{
	size_t sl = strlen(str), su = strlen(suffix);
	return (sl >= su) && (strcmp(str + sl - su, suffix) == 0);
}

static int parseReleaseObj(jparse_t *p, release_t *rel)
{
	memset(rel, 0, sizeof(*rel));
	char tagStr[MAX_TAG_LEN] = {0};
	int depth = 1;

	while (depth > 0) {
		jtok_t key = jp_next(p);
		if (key.type == JTOK_RBRACE) { depth--; continue; }
		if (key.type == JTOK_LBRACE) { depth++; continue; }
		if (key.type == JTOK_EOF) return -1;
		if (key.type == JTOK_COMMA) continue;
		if (key.type != JTOK_STRING) { jp_skipval(p); continue; }

		jtok_t colon = jp_next(p);
		if (colon.type != JTOK_COLON) continue;

		if (jp_iskey(&key, "tag_name")) {
			jtok_t val = jp_next(p);
			if (val.type == JTOK_STRING) {
				jp_copystr(&val, tagStr, sizeof(tagStr));
				jp_copystr(&val, rel->tag, sizeof(rel->tag));
			}
		} else if (jp_iskey(&key, "name")) {
			jtok_t val = jp_next(p);
			if (val.type == JTOK_STRING) {
				jp_copystr(&val, rel->name, sizeof(rel->name));
			}
		} else if (jp_iskey(&key, "body")) {
			jtok_t val = jp_next(p);
			if (val.type == JTOK_STRING) {
				jp_copystr_unescape(&val, rel->body, sizeof(rel->body));
			}
		} else if (jp_iskey(&key, "prerelease")) {
			jtok_t val = jp_next(p);
			rel->isPrerelease = (val.type == JTOK_TRUE) ? 1 : 0;
		} else if (jp_iskey(&key, "draft")) {
			jtok_t val = jp_next(p);
			rel->isDraft = (val.type == JTOK_TRUE) ? 1 : 0;
		} else if (jp_iskey(&key, "assets")) {
			jtok_t arr = jp_next(p);
			if (arr.type == JTOK_LBRACKET) {
				while (1) {
					jtok_t t = jp_next(p);
					if (t.type == JTOK_RBRACKET) break;
					if (t.type == JTOK_EOF) return -1;
					if (t.type == JTOK_COMMA) continue;

					if (t.type == JTOK_LBRACE) {
						char aname[128] = {0};
						char aurl[MAX_URL_LEN] = {0};
						long long asize = 0;

						while (1) {
							jtok_t ak = jp_next(p);
							if (ak.type == JTOK_RBRACE) break;
							if (ak.type == JTOK_EOF) return -1;
							if (ak.type == JTOK_COMMA) continue;
							if (ak.type != JTOK_STRING) continue;
							jtok_t ac = jp_next(p);
							if (ac.type != JTOK_COLON) continue;

							if (jp_iskey(&ak, "name")) {
								jtok_t av = jp_next(p);
								if (av.type == JTOK_STRING) jp_copystr(&av, aname, sizeof(aname));
							} else if (jp_iskey(&ak, "browser_download_url")) {
								jtok_t av = jp_next(p);
								if (av.type == JTOK_STRING) jp_copystr(&av, aurl, sizeof(aurl));
							} else if (jp_iskey(&ak, "size")) {
								jtok_t av = jp_next(p);
								if (av.type == JTOK_NUMBER) asize = strtoll(av.start, NULL, 10);
							} else {
								jp_skipval(p);
							}
						}

						if (str_ends_with(aname, ASSET_ZIP_SUFFIX)) {
							strncpy(rel->assetUrl, aurl, MAX_URL_LEN - 1);
							rel->assetUrl[MAX_URL_LEN - 1] = '\0';
							rel->assetSize = asize;
						} else if (str_ends_with(aname, ".zip.sha256")) {
							strncpy(rel->hashUrl, aurl, MAX_URL_LEN - 1);
							rel->hashUrl[MAX_URL_LEN - 1] = '\0';
						}
					}
				}
			}
		} else {
			jp_skipval(p);
		}
	}

	if (tagStr[0] != 'v' && strstr(tagStr, "-v") == NULL) {
		return -1;
	}
	if (versionParseTagStr(tagStr, &rel->version) != 0) {
		return -1;
	}

	/* Fallback URL if no zip asset was listed */
	if (!rel->assetUrl[0] && rel->tag[0]) {
		snprintf(rel->assetUrl, MAX_URL_LEN - 1,
			"https://github.com/%s/%s/releases/download/%s/PerfectDark-%s%s",
			GITHUB_OWNER, GITHUB_REPO, rel->tag, rel->tag, ASSET_ZIP_SUFFIX);
		rel->assetUrl[MAX_URL_LEN - 1] = '\0';
	}

	return 0;
}

static int parseReleasesJson(const char *json, release_t *out, int maxOut, int showDev)
{
	jparse_t p;
	p.pos = json;
	memset(&p.cur, 0, sizeof(p.cur));

	jtok_t arr = jp_next(&p);
	if (arr.type != JTOK_LBRACKET) return -1;

	int count = 0;
	while (count < maxOut) {
		jtok_t t = jp_next(&p);
		if (t.type == JTOK_RBRACKET) break;
		if (t.type == JTOK_EOF) break;
		if (t.type == JTOK_COMMA) continue;

		if (t.type == JTOK_LBRACE) {
			release_t rel;
			if (parseReleaseObj(&p, &rel) == 0 && !rel.isDraft) {
				if (!showDev && rel.isPrerelease) continue;
				out[count++] = rel;
			}
		}
	}

	/* Sort newest-first by version */
	for (int i = 1; i < count; i++) {
		release_t tmp = out[i];
		int j = i - 1;
		while (j >= 0 && versionCmp(&out[j].version, &tmp.version) < 0) {
			out[j + 1] = out[j];
			j--;
		}
		out[j + 1] = tmp;
	}
	return count;
}

/* ========================================================================
 * Settings file (Show Dev Releases persistence)
 * ======================================================================== */

static void settingsLoad(void)
{
	FILE *fp = fopen(g_App.settingsPath, "r");
	if (!fp) return;
	char line[128];
	while (fgets(line, sizeof(line), fp)) {
		char *nl = strpbrk(line, "\r\n");
		if (nl) *nl = '\0';
		if (strncmp(line, "showDevReleases=", 16) == 0) {
			g_App.showDevReleases = atoi(line + 16) ? 1 : 0;
		}
	}
	fclose(fp);
}

static void settingsSave(void)
{
	FILE *fp = fopen(g_App.settingsPath, "w");
	if (!fp) return;
	fprintf(fp, "showDevReleases=%d\n", g_App.showDevReleases ? 1 : 0);
	fclose(fp);
}

/* Try to pick up the preference from pd.ini if it exists and the standalone
 * settings file has not been written yet. That way launching Updater.exe on
 * an install that already has "Show Dev Releases" on inside the game
 * preserves that choice. */
static void showDevReleasesFromPdIni(void)
{
	char iniPath[MAX_PATH];
	snprintf(iniPath, sizeof(iniPath), "%s\\pd.ini", g_App.installDir);
	FILE *fp = fopen(iniPath, "r");
	if (!fp) return;
	int inUpdates = 0;
	char line[512];
	while (fgets(line, sizeof(line), fp)) {
		char *nl = strpbrk(line, "\r\n");
		if (nl) *nl = '\0';
		if (line[0] == '[') {
			inUpdates = (strcmp(line, "[Updates]") == 0);
			continue;
		}
		if (inUpdates && strncmp(line, "ShowDevReleases=", 16) == 0) {
			g_App.showDevReleases = atoi(line + 16) ? 1 : 0;
			break;
		}
	}
	fclose(fp);
}

/* ========================================================================
 * Path setup
 * ======================================================================== */

static void pathsDetect(void)
{
	GetModuleFileNameA(NULL, g_App.exePath, sizeof(g_App.exePath));
	strncpy(g_App.installDir, g_App.exePath, sizeof(g_App.installDir) - 1);
	g_App.installDir[sizeof(g_App.installDir) - 1] = '\0';
	char *lastSep = strrchr(g_App.installDir, '\\');
	if (!lastSep) lastSep = strrchr(g_App.installDir, '/');
	if (lastSep) *lastSep = '\0';

	snprintf(g_App.settingsPath,  sizeof(g_App.settingsPath),  "%s\\pd-updater.ini",   g_App.installDir);
	snprintf(g_App.updateZipPath, sizeof(g_App.updateZipPath), "%s\\pd.update.zip",    g_App.installDir);
	snprintf(g_App.stagingDir,    sizeof(g_App.stagingDir),    "%s\\pd_update_staging",g_App.installDir);
	snprintf(g_App.selfOldPath,   sizeof(g_App.selfOldPath),   "%s.old",               g_App.exePath);
}

/* ========================================================================
 * Worker threads
 * ======================================================================== */

static void setError(const char *msg)
{
	EnterCriticalSection(&g_App.cs);
	strncpy(g_App.errorMsg, msg, sizeof(g_App.errorMsg) - 1);
	g_App.errorMsg[sizeof(g_App.errorMsg) - 1] = '\0';
	LeaveCriticalSection(&g_App.cs);
}

static unsigned __stdcall checkThread(void *arg)
{
	(void)arg;
	char url[256];
	snprintf(url, sizeof(url),
		"https://api.github.com/repos/%s/%s/releases?per_page=100",
		GITHUB_OWNER, GITHUB_REPO);

	curl_buffer_t buf;
	long httpCode = 0;
	CURLcode res = curlGet(url, &buf, &httpCode);

	if (res != CURLE_OK) {
		char msg[256];
		snprintf(msg, sizeof(msg), "Network error: %s", curl_easy_strerror(res));
		setError(msg);
		if (buf.data) free(buf.data);
		PostMessage(g_App.hMain, WM_APP_CHECK_FAILED, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}
	if (!buf.data || buf.size == 0) {
		setError("Empty response from GitHub API");
		if (buf.data) free(buf.data);
		PostMessage(g_App.hMain, WM_APP_CHECK_FAILED, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}
	if (httpCode == 403) {
		setError("GitHub API rate limit exceeded -- retry in about an hour.");
		free(buf.data);
		PostMessage(g_App.hMain, WM_APP_CHECK_FAILED, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}
	if (httpCode != 200) {
		char msg[128];
		snprintf(msg, sizeof(msg), "GitHub API returned HTTP %ld", httpCode);
		setError(msg);
		free(buf.data);
		PostMessage(g_App.hMain, WM_APP_CHECK_FAILED, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	/* Always parse all non-draft releases; checkbox filtering happens in the UI */
	int count = parseReleasesJson(buf.data, g_App.scratchReleases, MAX_RELEASES, 1);
	free(buf.data);

	if (count < 0) {
		setError("Malformed JSON response (unexpected top-level token).");
		PostMessage(g_App.hMain, WM_APP_CHECK_FAILED, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	EnterCriticalSection(&g_App.cs);
	g_App.scratchCount = count;
	LeaveCriticalSection(&g_App.cs);

	PostMessage(g_App.hMain, WM_APP_CHECK_DONE, (WPARAM)count, 0);
	InterlockedExchange(&g_App.workerBusy, 0);
	return 0;
}

static unsigned __stdcall downloadThread(void *arg)
{
	release_t *rel = (release_t *)arg;
	InterlockedExchange64(&g_App.bytesDone, 0);
	InterlockedExchange64(&g_App.bytesTotal, rel->assetSize);
	PostMessage(g_App.hMain, WM_APP_DOWNLOAD_BEGIN, 0, 0);

	/* Grab SHA-256 sidecar if available */
	char expectedHash[SHA256_HEX_SIZE] = {0};
	int hasHash = 0;
	if (rel->hashUrl[0]) {
		curl_buffer_t hashBuf;
		CURLcode hres = curlGet(rel->hashUrl, &hashBuf, NULL);
		if (hres == CURLE_OK && hashBuf.data) {
			int i;
			for (i = 0; i < 64 && hashBuf.data[i] && !isspace((unsigned char)hashBuf.data[i]); i++) {
				expectedHash[i] = hashBuf.data[i];
			}
			expectedHash[i] = '\0';
			if (i == 64) hasHash = 1;
			free(hashBuf.data);
		}
	}

	FILE *fp = fopen(g_App.updateZipPath, "wb");
	if (!fp) {
		setError("Could not open update zip for writing.");
		PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	CURL *curl = curl_easy_init();
	if (!curl) {
		fclose(fp);
		DeleteFileA(g_App.updateZipPath);
		setError("libcurl initialisation failed.");
		PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	curl_file_ctx_t fctx;
	fctx.fp = fp;
	fctx.written = 0;

	curl_easy_setopt(curl, CURLOPT_URL, rel->assetUrl);
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curlFileWrite);
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, &fctx);
	curl_easy_setopt(curl, CURLOPT_USERAGENT, "PerfectDark-Updater/" UPDATER_VERSION_STRING);
	curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 600L);
	curlSetupTLS(curl);

	struct curl_slist *headers = NULL;
	headers = curl_slist_append(headers, "Accept: application/octet-stream");
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

	curl_easy_setopt(curl, CURLOPT_XFERINFOFUNCTION, curlXfer);
	curl_easy_setopt(curl, CURLOPT_XFERINFODATA, NULL);
	curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);

	CURLcode res = curl_easy_perform(curl);
	curl_slist_free_all(headers);
	curl_easy_cleanup(curl);
	fclose(fp);

	if (InterlockedCompareExchange(&g_App.cancelFlag, 0, 0)) {
		DeleteFileA(g_App.updateZipPath);
		setError("Download cancelled.");
		PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 0;
	}

	if (res != CURLE_OK) {
		DeleteFileA(g_App.updateZipPath);
		char msg[256];
		snprintf(msg, sizeof(msg), "Download failed: %s", curl_easy_strerror(res));
		setError(msg);
		PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	/* PK magic check */
	{
		FILE *fc = fopen(g_App.updateZipPath, "rb");
		unsigned char magic[4] = {0};
		if (fc) { fread(magic, 1, 4, fc); fclose(fc); }
		if (magic[0] != 0x50 || magic[1] != 0x4B || magic[2] != 0x03 || magic[3] != 0x04) {
			DeleteFileA(g_App.updateZipPath);
			setError("Downloaded file is not a valid ZIP archive.");
			PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
			InterlockedExchange(&g_App.workerBusy, 0);
			return 1;
		}
	}

	if (hasHash) {
		if (sha256VerifyFile(g_App.updateZipPath, expectedHash) != 1) {
			DeleteFileA(g_App.updateZipPath);
			setError("SHA-256 verification failed -- download may be corrupted.");
			PostMessage(g_App.hMain, WM_APP_DOWNLOAD_FAIL, 0, 0);
			InterlockedExchange(&g_App.workerBusy, 0);
			return 1;
		}
	}

	PostMessage(g_App.hMain, WM_APP_DOWNLOAD_DONE, 0, 0);
	InterlockedExchange(&g_App.workerBusy, 0);
	return 0;
}

/* ========================================================================
 * ZIP extraction + install (mirrors updater.c apply flow)
 * ======================================================================== */

static char s_ProtectedList[64][64];
static int s_ProtectedCount = 0;

static void buildProtectedList(const char *csv)
{
	char buf[512];
	strncpy(buf, csv, sizeof(buf) - 1);
	buf[sizeof(buf) - 1] = '\0';
	s_ProtectedCount = 0;
	char *p = buf;
	while (*p && s_ProtectedCount < 62) {
		while (*p == ' ' || *p == '\t') p++;
		if (!*p) break;
		char *comma = strchr(p, ',');
		if (comma) *comma = '\0';
		/* Trim trailing whitespace */
		size_t len = strlen(p);
		while (len > 0 && (p[len-1] == ' ' || p[len-1] == '\t')) p[--len] = '\0';
		if (len > 0) {
			strncpy(s_ProtectedList[s_ProtectedCount], p, 63);
			s_ProtectedList[s_ProtectedCount][63] = '\0';
			s_ProtectedCount++;
		}
		if (!comma) break;
		p = comma + 1;
	}
	/* pd.ini and the updater's own settings are always protected. */
	strcpy(s_ProtectedList[s_ProtectedCount++], "pd.ini");
	strcpy(s_ProtectedList[s_ProtectedCount++], "pd-updater.ini");
}

static int isProtectedRelPath(const char *relPath)
{
	char norm[MAX_PATH];
	int i;
	for (i = 0; relPath[i] && i < (int)(sizeof(norm) - 1); i++) {
		norm[i] = (relPath[i] == '\\') ? '/' : (char)tolower((unsigned char)relPath[i]);
	}
	norm[i] = '\0';
	for (int j = 0; j < s_ProtectedCount; j++) {
		size_t plen = strlen(s_ProtectedList[j]);
		char lprot[64];
		for (size_t k = 0; k < plen && k < sizeof(lprot) - 1; k++) {
			lprot[k] = (char)tolower((unsigned char)s_ProtectedList[j][k]);
		}
		lprot[plen] = '\0';
		if (strncmp(norm, lprot, plen) == 0 && (norm[plen] == '\0' || norm[plen] == '/')) {
			return 1;
		}
	}
	return 0;
}

static void postApplyStatus(const char *text)
{
	/* Copy the status line into errorMsg (reused as the latest status buffer)
	 * then post a tick message. UI thread reads the buffer. */
	EnterCriticalSection(&g_App.cs);
	strncpy(g_App.errorMsg, text, sizeof(g_App.errorMsg) - 1);
	g_App.errorMsg[sizeof(g_App.errorMsg) - 1] = '\0';
	LeaveCriticalSection(&g_App.cs);
	PostMessage(g_App.hMain, WM_APP_APPLY_TICK, 0, 0);
}

static int extractZipToStaging(const char *zipPath, const char *stagingDir)
{
	CreateDirectoryA(stagingDir, NULL);

	char escZip[1024], escStaging[1024];
	int j = 0;
	for (int i = 0; zipPath[i] && j < (int)sizeof(escZip) - 2; i++) {
		if (zipPath[i] == '\'') escZip[j++] = '\'';
		escZip[j++] = zipPath[i];
	}
	escZip[j] = '\0';
	j = 0;
	for (int i = 0; stagingDir[i] && j < (int)sizeof(escStaging) - 2; i++) {
		if (stagingDir[i] == '\'') escStaging[j++] = '\'';
		escStaging[j++] = stagingDir[i];
	}
	escStaging[j] = '\0';

	char cmd[2048];
	snprintf(cmd, sizeof(cmd),
		"powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass "
		"-Command \"Expand-Archive -LiteralPath '%s' -DestinationPath '%s' -Force\"",
		escZip, escStaging);

	STARTUPINFOA si;
	PROCESS_INFORMATION pi;
	memset(&si, 0, sizeof(si));
	memset(&pi, 0, sizeof(pi));
	si.cb = sizeof(si);

	if (!CreateProcessA(NULL, cmd, NULL, NULL, FALSE,
			CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP, NULL, NULL, &si, &pi)) {
		return -1;
	}

	WaitForSingleObject(pi.hProcess, 300000);
	DWORD exitCode = 1;
	GetExitCodeProcess(pi.hProcess, &exitCode);
	CloseHandle(pi.hProcess);
	CloseHandle(pi.hThread);
	return (exitCode == 0) ? 0 : -1;
}

static void copyDirRecursive(const char *srcDir, const char *dstDir)
{
	char pattern[MAX_PATH];
	snprintf(pattern, sizeof(pattern), "%s\\*", srcDir);
	WIN32_FIND_DATAA fd;
	HANDLE h = FindFirstFileA(pattern, &fd);
	if (h == INVALID_HANDLE_VALUE) return;
	do {
		if (strcmp(fd.cFileName, ".") == 0 || strcmp(fd.cFileName, "..") == 0) continue;
		char src[MAX_PATH], dst[MAX_PATH];
		snprintf(src, sizeof(src), "%s\\%s", srcDir, fd.cFileName);
		snprintf(dst, sizeof(dst), "%s\\%s", dstDir, fd.cFileName);
		if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
			CreateDirectoryA(dst, NULL);
			copyDirRecursive(src, dst);
		} else {
			CopyFileA(src, dst, FALSE);
		}
	} while (FindNextFileA(h, &fd));
	FindClose(h);
}

static void removeDirRecursive(const char *dir)
{
	char pattern[MAX_PATH];
	snprintf(pattern, sizeof(pattern), "%s\\*", dir);
	WIN32_FIND_DATAA fd;
	HANDLE h = FindFirstFileA(pattern, &fd);
	if (h != INVALID_HANDLE_VALUE) {
		do {
			if (strcmp(fd.cFileName, ".") == 0 || strcmp(fd.cFileName, "..") == 0) continue;
			char path[MAX_PATH];
			snprintf(path, sizeof(path), "%s\\%s", dir, fd.cFileName);
			if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) removeDirRecursive(path);
			else DeleteFileA(path);
		} while (FindNextFileA(h, &fd));
		FindClose(h);
	}
	RemoveDirectoryA(dir);
}

static void cleanupStaleFiles(const char *installDir, const char *stagingDir, const char *relBase)
{
	char searchPath[MAX_PATH];
	if (relBase[0]) snprintf(searchPath, sizeof(searchPath), "%s\\%s\\*", installDir, relBase);
	else            snprintf(searchPath, sizeof(searchPath), "%s\\*", installDir);

	WIN32_FIND_DATAA fd;
	HANDLE h = FindFirstFileA(searchPath, &fd);
	if (h == INVALID_HANDLE_VALUE) return;
	do {
		if (strcmp(fd.cFileName, ".") == 0 || strcmp(fd.cFileName, "..") == 0) continue;
		if (strcmp(fd.cFileName, "pd_update_staging") == 0) continue;
		{
			const char *fn = fd.cFileName;
			size_t fnl = strlen(fn);
			if (fnl > 4 && strcmp(fn + fnl - 4, ".old") == 0) continue;
			if (fnl > 4 && strcmp(fn + fnl - 4, ".zip") == 0) continue;
			if (fnl > 4 && strcmp(fn + fnl - 4, ".ver") == 0) continue;
		}

		char relPath[MAX_PATH];
		if (relBase[0]) snprintf(relPath, sizeof(relPath), "%s\\%s", relBase, fd.cFileName);
		else            snprintf(relPath, sizeof(relPath), "%s", fd.cFileName);

		if (isProtectedRelPath(relPath)) continue;

		char stagingPath[MAX_PATH];
		snprintf(stagingPath, sizeof(stagingPath), "%s\\%s", stagingDir, relPath);
		int inStaging = (GetFileAttributesA(stagingPath) != INVALID_FILE_ATTRIBUTES);

		if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
			if (inStaging) {
				cleanupStaleFiles(installDir, stagingDir, relPath);
			} else {
				char full[MAX_PATH];
				snprintf(full, sizeof(full), "%s\\%s", installDir, relPath);
				removeDirRecursive(full);
			}
		} else {
			if (!inStaging) {
				char full[MAX_PATH];
				snprintf(full, sizeof(full), "%s\\%s", installDir, relPath);
				DeleteFileA(full);
			}
		}
	} while (FindNextFileA(h, &fd));
	FindClose(h);
}

static unsigned __stdcall applyThread(void *arg)
{
	(void)arg;
	postApplyStatus("Extracting archive...");

	if (extractZipToStaging(g_App.updateZipPath, g_App.stagingDir) != 0) {
		setError("ZIP extraction failed (PowerShell Expand-Archive).");
		PostMessage(g_App.hMain, WM_APP_APPLY_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}

	/* Sanity: new PerfectDark.exe must exist and be a reasonable size. */
	char testExe[MAX_PATH];
	snprintf(testExe, sizeof(testExe), "%s\\PerfectDark.exe", g_App.stagingDir);
	if (GetFileAttributesA(testExe) == INVALID_FILE_ATTRIBUTES) {
		removeDirRecursive(g_App.stagingDir);
		setError("Extracted archive is missing PerfectDark.exe.");
		PostMessage(g_App.hMain, WM_APP_APPLY_FAIL, 0, 0);
		InterlockedExchange(&g_App.workerBusy, 0);
		return 1;
	}
	{
		HANDLE hExe = CreateFileA(testExe, GENERIC_READ, FILE_SHARE_READ,
			NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
		if (hExe != INVALID_HANDLE_VALUE) {
			LARGE_INTEGER sz; sz.QuadPart = 0;
			GetFileSizeEx(hExe, &sz);
			CloseHandle(hExe);
			if (sz.QuadPart < (1LL * 1024 * 1024)) {
				removeDirRecursive(g_App.stagingDir);
				setError("Extracted PerfectDark.exe looks truncated.");
				PostMessage(g_App.hMain, WM_APP_APPLY_FAIL, 0, 0);
				InterlockedExchange(&g_App.workerBusy, 0);
				return 1;
			}
		}
	}

	/* Only rename the running Updater.exe to .old if the zip actually
	 * ships a new copy -- otherwise we would brick the updater by renaming
	 * it out of the way with nothing to take its place. Windows allows
	 * renaming a running binary but not overwriting one, so the rename is
	 * the correct maneuver when a replacement is on its way. */
	const char *selfBasename = strrchr(g_App.exePath, '\\');
	selfBasename = selfBasename ? selfBasename + 1 : g_App.exePath;
	char stagingSelf[MAX_PATH];
	snprintf(stagingSelf, sizeof(stagingSelf), "%s\\%s", g_App.stagingDir, selfBasename);
	int zipHasNewSelf = (GetFileAttributesA(stagingSelf) != INVALID_FILE_ATTRIBUTES);
	if (zipHasNewSelf) {
		postApplyStatus("Freeing updater.exe...");
		MoveFileExA(g_App.exePath, g_App.selfOldPath,
			MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH);
	}

	postApplyStatus("Copying new files...");
	copyDirRecursive(g_App.stagingDir, g_App.installDir);

	postApplyStatus("Cleaning up stale files...");
	buildProtectedList(DEFAULT_PROTECTED);
	cleanupStaleFiles(g_App.installDir, g_App.stagingDir, "");

	postApplyStatus("Finalising...");
	removeDirRecursive(g_App.stagingDir);
	DeleteFileA(g_App.updateZipPath);
	/* Version sidecar left by a previous download via the in-game updater
	 * (if any) is also cleared. */
	char verSidecar[MAX_PATH];
	snprintf(verSidecar, sizeof(verSidecar), "%s.ver", g_App.updateZipPath);
	DeleteFileA(verSidecar);

	PostMessage(g_App.hMain, WM_APP_APPLY_DONE, 0, 0);
	InterlockedExchange(&g_App.workerBusy, 0);
	return 0;
}

static void cleanupSelfOld(void)
{
	/* Best-effort removal of a previous Updater.exe.old left behind by a
	 * prior successful run. Silently ignore failures -- the file may still
	 * be locked until the next reboot on some Windows versions. */
	DeleteFileA(g_App.selfOldPath);
}

/* ========================================================================
 * GUI helpers
 * ======================================================================== */

static HFONT makeFont(int height, int weight)
{
	return CreateFontA(height, 0, 0, 0, weight,
		FALSE, FALSE, FALSE, DEFAULT_CHARSET,
		OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
		CLEARTYPE_QUALITY, DEFAULT_PITCH | FF_SWISS, "Segoe UI");
}

static void setStatus(const char *fmt, ...)
{
	char buf[512];
	va_list ap;
	va_start(ap, fmt);
	vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);
	SetWindowTextA(g_App.hStatus, buf);
}

static void filterReleases(void)
{
	g_App.releaseCount = 0;
	for (int i = 0; i < g_App.allReleaseCount; i++) {
		if (!g_App.showDevReleases && g_App.allReleases[i].isPrerelease) continue;
		g_App.releases[g_App.releaseCount++] = g_App.allReleases[i];
	}
}

static void populateList(void)
{
	ListView_DeleteAllItems(g_App.hList);

	for (int i = 0; i < g_App.releaseCount; i++) {
		const release_t *r = &g_App.releases[i];
		char verStr[32];
		versionFmt(&r->version, verStr, sizeof(verStr));

		LVITEMA it = {0};
		it.mask = LVIF_TEXT;
		it.iItem = i;
		it.iSubItem = 0;
		it.pszText = verStr;
		int idx = (int)SendMessageA(g_App.hList, LVM_INSERTITEMA, 0, (LPARAM)&it);

		LVITEMA sub = {0};
		sub.mask = LVIF_TEXT;
		sub.iItem = idx;
		sub.iSubItem = 1;
		sub.pszText = (char *)(r->isPrerelease ? "Dev" : "Stable");
		SendMessageA(g_App.hList, LVM_SETITEMA, 0, (LPARAM)&sub);

		sub.iSubItem = 2;
		sub.pszText = (char *)(r->name[0] ? r->name : r->tag);
		SendMessageA(g_App.hList, LVM_SETITEMA, 0, (LPARAM)&sub);
	}

	if (g_App.releaseCount > 0) {
		/* Preselect newest */
		ListView_SetItemState(g_App.hList, 0, LVIS_SELECTED | LVIS_FOCUSED,
			LVIS_SELECTED | LVIS_FOCUSED);
		g_App.selectedIndex = 0;
		SetWindowTextA(g_App.hNotes, g_App.releases[0].body);
	} else {
		g_App.selectedIndex = -1;
		SetWindowTextA(g_App.hNotes, "");
	}

	/* Enable Update if we have a selection */
	EnableWindow(g_App.hBtnUpdate, g_App.releaseCount > 0);
}

static void showProgress(int visible)
{
	ShowWindow(g_App.hProgress, visible ? SW_SHOW : SW_HIDE);
}

/* ========================================================================
 * Window procedure
 * ======================================================================== */

static void onCheck(void);
static void onUpdate(void);
static void onClose(HWND hwnd);
static void layoutControls(HWND hwnd);

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
	switch (msg) {
	case WM_CTLCOLORDLG:
	case WM_CTLCOLORSTATIC: {
		HDC hdc = (HDC)wParam;
		SetBkMode(hdc, TRANSPARENT);
		SetTextColor(hdc, COL_TEXT);
		return (LRESULT)g_App.hBrushBg;
	}
	case WM_CTLCOLORBTN: {
		HDC hdc = (HDC)wParam;
		SetBkMode(hdc, TRANSPARENT);
		SetTextColor(hdc, COL_TEXT);
		return (LRESULT)g_App.hBrushBg;
	}
	case WM_CTLCOLOREDIT: {
		HDC hdc = (HDC)wParam;
		SetBkMode(hdc, OPAQUE);
		SetBkColor(hdc, COL_BG_ALT);
		SetTextColor(hdc, COL_TEXT);
		return (LRESULT)g_App.hBrushBgAlt;
	}
	case WM_ERASEBKGND: {
		HDC hdc = (HDC)wParam;
		RECT rc;
		GetClientRect(hwnd, &rc);
		FillRect(hdc, &rc, g_App.hBrushBg);
		return 1;
	}
	case WM_DRAWITEM: {
		DRAWITEMSTRUCT *dis = (DRAWITEMSTRUCT *)lParam;
		if (dis->CtlID == IDC_BTN_UPDATE && dis->CtlType == ODT_BUTTON) {
			int pressed = (dis->itemState & ODS_SELECTED) ? 1 : 0;
			int disabled = (dis->itemState & ODS_DISABLED) ? 1 : 0;
			int focus   = (dis->itemState & ODS_FOCUS) ? 1 : 0;

			COLORREF fill;
			if (disabled) fill = RGB(0x2A, 0x2C, 0x32);
			else if (pressed) fill = COL_ACCENT_PRESSED;
			else fill = COL_ACCENT;

			HBRUSH br = CreateSolidBrush(fill);
			FillRect(dis->hDC, &dis->rcItem, br);
			DeleteObject(br);

			if (focus) {
				HPEN pen = CreatePen(PS_SOLID, 1, RGB(0xFF, 0xFF, 0xFF));
				HPEN old = (HPEN)SelectObject(dis->hDC, pen);
				HBRUSH oldBr = (HBRUSH)SelectObject(dis->hDC, GetStockObject(NULL_BRUSH));
				Rectangle(dis->hDC, dis->rcItem.left + 2, dis->rcItem.top + 2,
					dis->rcItem.right - 2, dis->rcItem.bottom - 2);
				SelectObject(dis->hDC, old);
				SelectObject(dis->hDC, oldBr);
				DeleteObject(pen);
			}

			char caption[64];
			GetWindowTextA(dis->hwndItem, caption, sizeof(caption));
			SetBkMode(dis->hDC, TRANSPARENT);
			SetTextColor(dis->hDC, disabled ? COL_TEXT_DIM : RGB(0xFF, 0xFF, 0xFF));
			HFONT oldFont = (HFONT)SelectObject(dis->hDC, g_App.hFontUI);
			DrawTextA(dis->hDC, caption, -1, &dis->rcItem,
				DT_CENTER | DT_VCENTER | DT_SINGLELINE);
			SelectObject(dis->hDC, oldFont);
			return TRUE;
		}
		return FALSE;
	}
	case WM_NOTIFY: {
		NMHDR *n = (NMHDR *)lParam;
		if (n->idFrom == IDC_LIST_RELEASES && n->code == LVN_ITEMCHANGED) {
			NMLISTVIEW *nlv = (NMLISTVIEW *)lParam;
			if ((nlv->uNewState & LVIS_SELECTED) && nlv->iItem >= 0 &&
					nlv->iItem < g_App.releaseCount) {
				g_App.selectedIndex = nlv->iItem;
				SetWindowTextA(g_App.hNotes, g_App.releases[nlv->iItem].body);
			}
		} else if (n->idFrom == IDC_LIST_RELEASES && n->code == NM_CUSTOMDRAW) {
			NMLVCUSTOMDRAW *cd = (NMLVCUSTOMDRAW *)lParam;
			if (cd->nmcd.dwDrawStage == CDDS_PREPAINT) {
				return CDRF_NOTIFYITEMDRAW;
			}
			if (cd->nmcd.dwDrawStage == CDDS_ITEMPREPAINT) {
				int row = (int)cd->nmcd.dwItemSpec;
				cd->clrText = COL_TEXT;
				if (row == g_App.selectedIndex) {
					cd->clrTextBk = COL_ACCENT_PRESSED;
				} else if (row % 2 == 0) {
					cd->clrTextBk = COL_BG_ALT;
				} else {
					cd->clrTextBk = COL_BG;
				}
				return CDRF_NEWFONT;
			}
		}
		break;
	}
	case WM_COMMAND: {
		int id = LOWORD(wParam);
		switch (id) {
		case IDC_SHOW_DEV_RELEASES:
			if (!g_App.workerBusy) {
				LRESULT state = SendMessage(g_App.hShowDevReleases, BM_GETCHECK, 0, 0);
				g_App.showDevReleases = (state == BST_CHECKED) ? 1 : 0;
				settingsSave();
				if (g_App.allReleaseCount > 0) {
					filterReleases();
					populateList();
				}
			}
			break;
		case IDC_BTN_CHECK:
			onCheck();
			break;
		case IDC_BTN_UPDATE:
			onUpdate();
			break;
		case IDC_BTN_CLOSE:
			onClose(hwnd);
			break;
		}
		break;
	}
	case WM_APP_CHECK_DONE: {
		int count = (int)wParam;
		EnterCriticalSection(&g_App.cs);
		memcpy(g_App.allReleases, g_App.scratchReleases, sizeof(release_t) * count);
		g_App.allReleaseCount = count;
		LeaveCriticalSection(&g_App.cs);
		filterReleases();
		populateList();
		EnableWindow(g_App.hBtnCheck, TRUE);
		if (g_App.releaseCount == 0) {
			setStatus("No %s releases found.",
				g_App.showDevReleases ? "stable or dev" : "stable");
		} else {
			pdver_t newest = g_App.releases[0].version;
			if (versionCmp(&newest, &g_App.currentVersion) > 0) {
				char v[32]; versionFmt(&newest, v, sizeof(v));
				setStatus("Update available: v%s (you have v%s).", v, g_App.versionStr);
			} else {
				setStatus("You are up to date.");
			}
		}
		break;
	}
	case WM_APP_CHECK_FAILED:
		EnableWindow(g_App.hBtnCheck, TRUE);
		setStatus("%s", g_App.errorMsg);
		break;
	case WM_APP_DOWNLOAD_BEGIN:
		showProgress(1);
		SendMessage(g_App.hProgress, PBM_SETRANGE32, 0, 1000);
		SendMessage(g_App.hProgress, PBM_SETPOS, 0, 0);
		setStatus("Downloading...");
		break;
	case WM_APP_DOWNLOAD_TICK: {
		LONGLONG done = InterlockedCompareExchange64(&g_App.bytesDone, 0, 0);
		LONGLONG total = InterlockedCompareExchange64(&g_App.bytesTotal, 0, 0);
		if (total > 0) {
			int pct = (int)((done * 1000) / total);
			SendMessage(g_App.hProgress, PBM_SETPOS, (WPARAM)pct, 0);
			double mbDone = (double)done / (1024.0 * 1024.0);
			double mbTotal = (double)total / (1024.0 * 1024.0);
			setStatus("Downloading...  %.1f / %.1f MB  (%d%%)",
				mbDone, mbTotal, pct / 10);
		} else {
			double mbDone = (double)done / (1024.0 * 1024.0);
			setStatus("Downloading...  %.1f MB", mbDone);
		}
		break;
	}
	case WM_APP_DOWNLOAD_DONE:
		SendMessage(g_App.hProgress, PBM_SETPOS, 1000, 0);
		setStatus("Download complete. Installing...");
		/* Kick off the apply thread. */
		InterlockedExchange(&g_App.workerBusy, 1);
		g_App.hWorker = (HANDLE)_beginthreadex(NULL, 0, applyThread, NULL, 0, NULL);
		break;
	case WM_APP_DOWNLOAD_FAIL:
		showProgress(0);
		EnableWindow(g_App.hBtnUpdate, TRUE);
		EnableWindow(g_App.hBtnCheck, TRUE);
		setStatus("Download failed: %s", g_App.errorMsg);
		MessageBoxA(hwnd, g_App.errorMsg, "Download failed", MB_ICONERROR | MB_OK);
		break;
	case WM_APP_APPLY_TICK:
		setStatus("%s", g_App.errorMsg);
		break;
	case WM_APP_APPLY_DONE: {
		showProgress(0);
		setStatus("Update installed. Launch PerfectDark.exe to play.");
		EnableWindow(g_App.hBtnCheck, TRUE);
		EnableWindow(g_App.hBtnUpdate, FALSE);
		int which = MessageBoxA(hwnd,
			"Update installed successfully.\n\nLaunch Perfect Dark now?",
			"Update complete", MB_ICONINFORMATION | MB_YESNO);
		if (which == IDYES) {
			char gamePath[MAX_PATH];
			snprintf(gamePath, sizeof(gamePath), "%s\\PerfectDark.exe", g_App.installDir);
			ShellExecuteA(NULL, "open", gamePath, NULL, g_App.installDir, SW_SHOWNORMAL);
		}
		break;
	}
	case WM_APP_APPLY_FAIL:
		showProgress(0);
		EnableWindow(g_App.hBtnUpdate, TRUE);
		EnableWindow(g_App.hBtnCheck, TRUE);
		setStatus("Install failed: %s", g_App.errorMsg);
		MessageBoxA(hwnd, g_App.errorMsg, "Install failed", MB_ICONERROR | MB_OK);
		break;
	case WM_SIZE:
		layoutControls(hwnd);
		InvalidateRect(hwnd, NULL, TRUE);
		break;
	case WM_GETMINMAXINFO: {
		/*
		 * Enforce a minimum window size large enough to keep every control
		 * (including the docked Update/Close buttons) visible. The values
		 * include the non-client frame so they apply to the outer window
		 * rect that WM_GETMINMAXINFO operates on.
		 */
		MINMAXINFO *mmi = (MINMAXINFO *)lParam;
		RECT rc = {0, 0, WINDOW_CLIENT_W, WINDOW_CLIENT_H};
		DWORD style = (DWORD)GetWindowLongPtr(hwnd, GWL_STYLE);
		AdjustWindowRect(&rc, style, FALSE);
		mmi->ptMinTrackSize.x = rc.right - rc.left;
		mmi->ptMinTrackSize.y = rc.bottom - rc.top;
		return 0;
	}
	case WM_CLOSE:
		onClose(hwnd);
		break;
	case WM_DESTROY:
		PostQuitMessage(0);
		break;
	}

	return DefWindowProc(hwnd, msg, wParam, lParam);
}

static void onCheck(void)
{
	if (InterlockedCompareExchange(&g_App.workerBusy, 1, 0)) return;
	EnableWindow(g_App.hBtnCheck, FALSE);
	EnableWindow(g_App.hBtnUpdate, FALSE);
	ListView_DeleteAllItems(g_App.hList);
	SetWindowTextA(g_App.hNotes, "");
	setStatus("Checking GitHub...");
	g_App.hWorker = (HANDLE)_beginthreadex(NULL, 0, checkThread, NULL, 0, NULL);
}

static void onUpdate(void)
{
	if (g_App.selectedIndex < 0 || g_App.selectedIndex >= g_App.releaseCount) {
		MessageBoxA(g_App.hMain, "Select a release from the list first.",
			APP_TITLE, MB_ICONINFORMATION | MB_OK);
		return;
	}
	if (InterlockedCompareExchange(&g_App.workerBusy, 1, 0)) return;

	release_t *r = &g_App.releases[g_App.selectedIndex];
	char verStr[32]; versionFmt(&r->version, verStr, sizeof(verStr));
	char prompt[512];
	snprintf(prompt, sizeof(prompt),
		"Download and install v%s (%s) now?\n\n"
		"Files in mods/, data/, extracted/, saves/ and pd.ini are preserved.\n"
		"All other files in this folder are replaced.",
		verStr, r->isPrerelease ? "Dev" : "Stable");

	if (MessageBoxA(g_App.hMain, prompt, "Confirm update",
			MB_ICONQUESTION | MB_OKCANCEL) != IDOK) {
		InterlockedExchange(&g_App.workerBusy, 0);
		return;
	}

	EnableWindow(g_App.hBtnCheck, FALSE);
	EnableWindow(g_App.hBtnUpdate, FALSE);
	InterlockedExchange(&g_App.cancelFlag, 0);
	g_App.hWorker = (HANDLE)_beginthreadex(NULL, 0, downloadThread, r, 0, NULL);
}

static void onClose(HWND hwnd)
{
	if (InterlockedCompareExchange(&g_App.workerBusy, 0, 0)) {
		if (MessageBoxA(hwnd,
				"An update is in progress. Cancel and quit?",
				APP_TITLE, MB_ICONWARNING | MB_YESNO) != IDYES) {
			return;
		}
		InterlockedExchange(&g_App.cancelFlag, 1);
	}
	DestroyWindow(hwnd);
}

/* ========================================================================
 * Window creation
 * ======================================================================== */

/*
 * Layout constants -- shared by createControls() (initial creation) and
 * layoutControls() (WM_SIZE re-anchoring). Keep these in one place so the
 * docked-footer pattern stays consistent across both code paths.
 */
#define UI_PAD          12
#define UI_TITLE_H      28
#define UI_ROW_H        20
#define UI_BTN_W        110
#define UI_BTN_H        32
#define UI_CHECK_BTN_W  160
#define UI_CHECK_BTN_H  30
#define UI_CHK_W        200
#define UI_LIST_H       160
#define UI_PROG_H       18
#define UI_STATUS_H     20
#define UI_NOTES_MIN_H  60

/*
 * Re-anchor every child control based on the current client rect.
 *
 * Top-anchored: title, version + dev-releases checkbox, Check button,
 *               "Available releases:" label, releases list view,
 *               "Release notes:" label.
 * Bottom-anchored: Update + Close action buttons, status text, progress bar.
 * Stretch-fill: notes edit box absorbs all leftover vertical space.
 *
 * This is the docked-footer pattern: the action row is pinned to the bottom
 * of the client area, so resizing or DPI variation can never clip it.
 */
static void layoutControls(HWND hwnd)
{
	if (!g_App.hMain) return;

	RECT rc;
	GetClientRect(hwnd, &rc);
	const int clientW = rc.right - rc.left;
	const int clientH = rc.bottom - rc.top;
	const int contentW = clientW - 2 * UI_PAD;
	if (contentW <= 0 || clientH <= 0) return;

	HDWP hdwp = BeginDeferWindowPos(13);

	/* --- Bottom-anchored row: action buttons (right-justified). --- */
	int btnY    = clientH - UI_PAD - UI_BTN_H;
	int closeX  = clientW - UI_PAD - UI_BTN_W;
	int updateX = closeX - 8 - UI_BTN_W;
	if (g_App.hBtnClose) {
		hdwp = DeferWindowPos(hdwp, g_App.hBtnClose, NULL,
			closeX, btnY, UI_BTN_W, UI_BTN_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	if (g_App.hBtnUpdate) {
		hdwp = DeferWindowPos(hdwp, g_App.hBtnUpdate, NULL,
			updateX, btnY, UI_BTN_W, UI_BTN_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}

	/* Status text just above the buttons (full width). */
	int statusY = btnY - 8 - UI_STATUS_H;
	if (g_App.hStatus) {
		hdwp = DeferWindowPos(hdwp, g_App.hStatus, NULL,
			UI_PAD, statusY, contentW, UI_STATUS_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}

	/* Progress bar just above status (full width). */
	int progY = statusY - 4 - UI_PROG_H;
	if (g_App.hProgress) {
		hdwp = DeferWindowPos(hdwp, g_App.hProgress, NULL,
			UI_PAD, progY, contentW, UI_PROG_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}

	/* --- Top-anchored. --- */
	int y = UI_PAD;

	if (g_App.hTitle) {
		hdwp = DeferWindowPos(hdwp, g_App.hTitle, NULL,
			UI_PAD, y, contentW, UI_TITLE_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += UI_TITLE_H + 6;

	/* Version label (left) + Show Dev Releases checkbox (right). */
	int chkX = clientW - UI_PAD - UI_CHK_W;
	int verW = chkX - UI_PAD - 8;
	if (verW < 100) verW = 100;
	if (g_App.hCurrentVer) {
		hdwp = DeferWindowPos(hdwp, g_App.hCurrentVer, NULL,
			UI_PAD, y, verW, UI_ROW_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	if (g_App.hShowDevReleases) {
		hdwp = DeferWindowPos(hdwp, g_App.hShowDevReleases, NULL,
			chkX, y, UI_CHK_W, UI_ROW_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += 30;

	if (g_App.hBtnCheck) {
		hdwp = DeferWindowPos(hdwp, g_App.hBtnCheck, NULL,
			UI_PAD, y, UI_CHECK_BTN_W, UI_CHECK_BTN_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += UI_CHECK_BTN_H + 8;

	if (g_App.hLblReleases) {
		hdwp = DeferWindowPos(hdwp, g_App.hLblReleases, NULL,
			UI_PAD, y, contentW, 18, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += 20;

	if (g_App.hList) {
		hdwp = DeferWindowPos(hdwp, g_App.hList, NULL,
			UI_PAD, y, contentW, UI_LIST_H, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += UI_LIST_H + 12;

	if (g_App.hLblNotes) {
		hdwp = DeferWindowPos(hdwp, g_App.hLblNotes, NULL,
			UI_PAD, y, contentW, 18, SWP_NOZORDER | SWP_NOACTIVATE);
	}
	y += 20;

	/* Notes edit box stretches to fill the gap between top stack and progress bar. */
	int notesTop = y;
	int notesH   = progY - 12 - notesTop;
	if (notesH < UI_NOTES_MIN_H) notesH = UI_NOTES_MIN_H;
	if (g_App.hNotes) {
		hdwp = DeferWindowPos(hdwp, g_App.hNotes, NULL,
			UI_PAD, notesTop, contentW, notesH, SWP_NOZORDER | SWP_NOACTIVATE);
	}

	if (hdwp) EndDeferWindowPos(hdwp);

	/* Resize the list view's "Title" column to absorb the new client width. */
	if (g_App.hList) {
		LVCOLUMNA col = {0};
		col.mask = LVCF_WIDTH;
		col.cx = contentW - 110 - 90 - 24;
		if (col.cx > 50) {
			SendMessageA(g_App.hList, LVM_SETCOLUMNA, 2, (LPARAM)&col);
		}
	}
}

static void createControls(HWND hwnd)
{
	const int pad = UI_PAD;
	const int winW = WINDOW_CLIENT_W;
	int y = pad;

	/* Header label */
	g_App.hTitle = CreateWindowA("STATIC", "Perfect Dark 2 Updater",
		WS_CHILD | WS_VISIBLE | SS_LEFT,
		pad, y, winW - 2 * pad, 28,
		hwnd, (HMENU)(INT_PTR)IDC_TITLE, GetModuleHandle(NULL), NULL);
	SendMessage(g_App.hTitle, WM_SETFONT, (WPARAM)g_App.hFontTitle, TRUE);
	y += 34;

	char verLine[128];
	snprintf(verLine, sizeof(verLine), "Installed version: v%s", g_App.versionStr);
	g_App.hCurrentVer = CreateWindowA("STATIC", verLine,
		WS_CHILD | WS_VISIBLE | SS_LEFT,
		pad, y, 380, 20,
		hwnd, (HMENU)(INT_PTR)IDC_CURRENT_VERSION, GetModuleHandle(NULL), NULL);

	/* "Show Dev Releases" checkbox (right side of header row) */
	int chkW = UI_CHK_W;
	int chkX = winW - pad - chkW;
	g_App.hShowDevReleases = CreateWindowA("BUTTON", "Show Dev Releases",
		WS_CHILD | WS_VISIBLE | BS_AUTOCHECKBOX,
		chkX, y, chkW, 20,
		hwnd, (HMENU)(INT_PTR)IDC_SHOW_DEV_RELEASES, GetModuleHandle(NULL), NULL);
	SendMessage(g_App.hShowDevReleases,
		BM_SETCHECK, g_App.showDevReleases ? BST_CHECKED : BST_UNCHECKED, 0);

	y += 30;

	/* Check for Updates button */
	g_App.hBtnCheck = CreateWindowA("BUTTON", "Check for Updates",
		WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
		pad, y, UI_CHECK_BTN_W, UI_CHECK_BTN_H,
		hwnd, (HMENU)(INT_PTR)IDC_BTN_CHECK, GetModuleHandle(NULL), NULL);
	y += UI_CHECK_BTN_H + 8;

	/* Releases list */
	g_App.hLblReleases = CreateWindowA("STATIC", "Available releases:",
		WS_CHILD | WS_VISIBLE | SS_LEFT,
		pad, y, 200, 18,
		hwnd, (HMENU)(INT_PTR)IDC_LBL_RELEASES, GetModuleHandle(NULL), NULL);
	y += 20;

	int listH = UI_LIST_H;
	g_App.hList = CreateWindowExA(WS_EX_CLIENTEDGE, WC_LISTVIEWA, "",
		WS_CHILD | WS_VISIBLE | LVS_REPORT | LVS_SINGLESEL | LVS_SHOWSELALWAYS,
		pad, y, winW - 2 * pad, listH,
		hwnd, (HMENU)(INT_PTR)IDC_LIST_RELEASES, GetModuleHandle(NULL), NULL);
	ListView_SetExtendedListViewStyle(g_App.hList,
		LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES | LVS_EX_DOUBLEBUFFER);
	ListView_SetBkColor(g_App.hList, COL_BG);
	ListView_SetTextBkColor(g_App.hList, COL_BG);
	ListView_SetTextColor(g_App.hList, COL_TEXT);

	{
		LVCOLUMNA col = {0};
		col.mask = LVCF_TEXT | LVCF_WIDTH | LVCF_SUBITEM;

		col.pszText = (char *)"Version";
		col.cx = 110;
		col.iSubItem = 0;
		SendMessageA(g_App.hList, LVM_INSERTCOLUMNA, 0, (LPARAM)&col);

		col.pszText = (char *)"Type";
		col.cx = 90;
		col.iSubItem = 1;
		SendMessageA(g_App.hList, LVM_INSERTCOLUMNA, 1, (LPARAM)&col);

		col.pszText = (char *)"Title";
		col.cx = winW - 2 * pad - 110 - 90 - 24;
		col.iSubItem = 2;
		SendMessageA(g_App.hList, LVM_INSERTCOLUMNA, 2, (LPARAM)&col);
	}

	y += listH + 12;

	/* Release notes */
	g_App.hLblNotes = CreateWindowA("STATIC", "Release notes:",
		WS_CHILD | WS_VISIBLE | SS_LEFT,
		pad, y, 200, 18,
		hwnd, (HMENU)(INT_PTR)IDC_LBL_NOTES, GetModuleHandle(NULL), NULL);
	y += 20;

	/*
	 * Initial notes height is recomputed by layoutControls() once we know the
	 * real client rect; this seed value is just enough to give a sensible
	 * appearance before the first WM_SIZE fires.
	 */
	int notesH = 140;
	g_App.hNotes = CreateWindowExA(WS_EX_CLIENTEDGE, "EDIT", "",
		WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_READONLY | WS_VSCROLL,
		pad, y, winW - 2 * pad, notesH,
		hwnd, (HMENU)(INT_PTR)IDC_RELEASE_NOTES, GetModuleHandle(NULL), NULL);

	/*
	 * Progress / status / action buttons are docked to the bottom by
	 * layoutControls(); their initial create-time positions are placeholders
	 * that get replaced on the very first WM_SIZE.
	 */
	g_App.hProgress = CreateWindowA(PROGRESS_CLASSA, "",
		WS_CHILD,
		pad, 0, winW - 2 * pad, UI_PROG_H,
		hwnd, (HMENU)(INT_PTR)IDC_PROGRESS, GetModuleHandle(NULL), NULL);
	SendMessage(g_App.hProgress, PBM_SETBARCOLOR, 0, (LPARAM)COL_ACCENT);
	SendMessage(g_App.hProgress, PBM_SETBKCOLOR, 0, (LPARAM)COL_BG_ALT);

	g_App.hStatus = CreateWindowA("STATIC", "",
		WS_CHILD | WS_VISIBLE | SS_LEFT | SS_ENDELLIPSIS,
		pad, 0, winW - 2 * pad, UI_STATUS_H,
		hwnd, (HMENU)(INT_PTR)IDC_STATUS, GetModuleHandle(NULL), NULL);

	g_App.hBtnUpdate = CreateWindowA("BUTTON", "Update",
		WS_CHILD | WS_VISIBLE | BS_OWNERDRAW,
		0, 0, UI_BTN_W, UI_BTN_H,
		hwnd, (HMENU)(INT_PTR)IDC_BTN_UPDATE, GetModuleHandle(NULL), NULL);
	EnableWindow(g_App.hBtnUpdate, FALSE);

	g_App.hBtnClose = CreateWindowA("BUTTON", "Close",
		WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
		0, 0, UI_BTN_W, UI_BTN_H,
		hwnd, (HMENU)(INT_PTR)IDC_BTN_CLOSE, GetModuleHandle(NULL), NULL);

	/* Apply UI font everywhere except the header title (already styled) */
	HWND child = GetWindow(hwnd, GW_CHILD);
	while (child) {
		if (child != g_App.hTitle) {
			SendMessage(child, WM_SETFONT, (WPARAM)g_App.hFontUI, TRUE);
		}
		child = GetWindow(child, GW_HWNDNEXT);
	}

	/*
	 * Apply the docked layout immediately so controls are correctly placed
	 * even before Windows delivers its first WM_SIZE.
	 */
	layoutControls(hwnd);
}

static int runGui(HINSTANCE hInstance)
{
	INITCOMMONCONTROLSEX icc = {0};
	icc.dwSize = sizeof(icc);
	icc.dwICC = ICC_LISTVIEW_CLASSES | ICC_PROGRESS_CLASS | ICC_STANDARD_CLASSES;
	InitCommonControlsEx(&icc);

	g_App.hBrushBg    = CreateSolidBrush(COL_BG);
	g_App.hBrushBgAlt = CreateSolidBrush(COL_BG_ALT);
	g_App.hFontUI     = makeFont(-14, FW_NORMAL);
	g_App.hFontTitle  = makeFont(-22, FW_SEMIBOLD);
	InitializeCriticalSection(&g_App.cs);

	WNDCLASSEXA wc = {0};
	wc.cbSize = sizeof(wc);
	wc.style = CS_HREDRAW | CS_VREDRAW;
	wc.lpfnWndProc = WndProc;
	wc.hInstance = hInstance;
	wc.hCursor = LoadCursor(NULL, IDC_ARROW);
	wc.hbrBackground = g_App.hBrushBg;
	wc.lpszClassName = APP_WINDOW_CLASS;
	wc.hIcon = LoadIcon(NULL, IDI_APPLICATION);
	wc.hIconSm = LoadIcon(NULL, IDI_APPLICATION);

	if (!RegisterClassExA(&wc)) {
		MessageBoxA(NULL, "Failed to register window class.", APP_TITLE, MB_ICONERROR);
		return 1;
	}

	int winW = WINDOW_CLIENT_W;
	/*
	 * Keep the window resizable (WS_THICKFRAME) so the docked layout can
	 * absorb whatever size the user picks; WM_GETMINMAXINFO clamps the
	 * floor so the bottom action row never disappears below the client
	 * edge. Maximise stays disabled to keep the dialog at a sensible size.
	 */
	DWORD winStyle = (WS_OVERLAPPEDWINDOW & ~WS_MAXIMIZEBOX) | WS_VISIBLE;
	RECT adjRc = {0, 0, winW, WINDOW_CLIENT_H};
	AdjustWindowRect(&adjRc, winStyle & ~WS_VISIBLE, FALSE);
	int winH = adjRc.bottom - adjRc.top;
	RECT workArea = {0};
	SystemParametersInfo(SPI_GETWORKAREA, 0, &workArea, 0);
	int winX = (workArea.right  - workArea.left - winW) / 2 + workArea.left;
	int winY = (workArea.bottom - workArea.top  - winH) / 2 + workArea.top;

	g_App.hMain = CreateWindowExA(0, APP_WINDOW_CLASS, APP_TITLE,
		winStyle,
		winX, winY, winW, winH,
		NULL, NULL, hInstance, NULL);

	if (!g_App.hMain) {
		MessageBoxA(NULL, "Failed to create main window.", APP_TITLE, MB_ICONERROR);
		return 1;
	}

	createControls(g_App.hMain);
	setStatus("Checking for updates...");
	PostMessage(g_App.hMain, WM_COMMAND, MAKEWPARAM(IDC_BTN_CHECK, BN_CLICKED),
		(LPARAM)g_App.hBtnCheck);

	MSG msg;
	while (GetMessage(&msg, NULL, 0, 0) > 0) {
		if (!IsDialogMessage(g_App.hMain, &msg)) {
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}
	}

	DeleteObject(g_App.hBrushBg);
	DeleteObject(g_App.hBrushBgAlt);
	DeleteObject(g_App.hFontUI);
	DeleteObject(g_App.hFontTitle);
	DeleteCriticalSection(&g_App.cs);
	return 0;
}

/* ========================================================================
 * Entry point
 * ======================================================================== */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInst, LPSTR cmdLine, int nShow)
{
	(void)hPrevInst; (void)cmdLine; (void)nShow;

	memset(&g_App, 0, sizeof(g_App));
	g_App.showDevReleases = 0;
	g_App.selectedIndex = -1;
	g_App.currentVersion.major = VERSION_MAJOR;
	g_App.currentVersion.minor = VERSION_MINOR;
	g_App.currentVersion.patch = VERSION_PATCH;
	versionFmt(&g_App.currentVersion, g_App.versionStr, sizeof(g_App.versionStr));

	pathsDetect();
	showDevReleasesFromPdIni();
	settingsLoad();
	cleanupSelfOld();

	curl_global_init(CURL_GLOBAL_DEFAULT);
	int rc = runGui(hInstance);
	curl_global_cleanup();
	return rc;
}
