/**
 * assetcatalog_resolve.h -- Standalone catalog-driven file resolution
 *
 * D3R-5: The catalog is the single source of truth for mod stage files.
 *
 * When a mod stage is being loaded, this module redirects file requests
 * to the catalog component's actual files. For bgdata files (geometry,
 * pads, tiles), it matches by ROLE (suffix) not by filename -- so even
 * if the legacy g_Stages[] has wrong file IDs, the right files load.
 *
 * Architecture:
 *   - Completely standalone: does not modify g_Stages[], modmgr, or any
 *     legacy data structures.
 *   - Stage context: lvReset() calls assetCatalogActivateStage() to set
 *     which catalog component (if any) should resolve files.
 *   - Smart bgdata redirect: matches by suffix (.seg, _padsZ, _tilesZ)
 *     to always serve the component's actual files.
 *   - Exact match fallback for non-bgdata files (textures, props, etc.).
 *   - Falls through silently if no catalog component applies.
 *
 * This module coexists with the legacy mod system. Both can resolve files;
 * the catalog gets first priority. Over time (D3R-11), the legacy system
 * is removed and the catalog becomes the sole resolver.
 */

#ifndef _IN_ASSETCATALOG_RESOLVE_H
#define _IN_ASSETCATALOG_RESOLVE_H

#include <PR/ultratypes.h>
#include "assetcatalog.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Find a non-bundled ASSET_MAP entry by stagenum.
 * Scans all enabled map entries for one matching the given stagenum.
 * Returns const pointer to the entry, or NULL if no mod component found.
 * Base game stages (bundled=1) are excluded -- they use the legacy path.
 */
const struct asset_entry *assetCatalogFindModMapByStagenum(s32 stagenum);

/**
 * Set the active catalog stage for file resolution.
 * Scans the component's bgdata directory to discover actual files, then
 * uses those for role-based redirect during loading. This is the core
 * of "catalog as source of truth" -- the component's files always win,
 * regardless of what the legacy system's file IDs resolve to.
 *
 * Call at the start of stage loading (e.g., in lvReset()).
 * Pass -1 or a base-game stagenum to deactivate.
 */
void assetCatalogActivateStage(s32 stagenum);

/**
 * Clear the active stage context.
 * Call when stage loading is complete or when returning to menus.
 */
void assetCatalogDeactivateStage(void);

/**
 * Resolve a relative file path through the active catalog component.
 *
 * For bgdata files: matches by role suffix (.seg, _padsZ, _tilesZ, etc.)
 * and returns the component's actual file for that role -- even if the
 * requested filename differs (fixes B-17).
 *
 * For other files: checks if the exact file exists in the component dir.
 *
 * Returns full path if found, NULL otherwise (falls through to legacy).
 * The returned pointer is to a static buffer -- valid until the next call.
 *
 * @param relPath  Relative path as generated by romdata (e.g., "files/bgdata/bg_arec.seg")
 * @return         Full path to file in component directory, or NULL
 */
const char *assetCatalogResolvePath(const char *relPath);

#ifdef __cplusplus
}
#endif

#endif /* _IN_ASSETCATALOG_RESOLVE_H */
