/**
 * assetcatalog_resolve.h -- Standalone catalog-driven file resolution
 *
 * D3R-5: Provides context-aware file resolution for mod stage loading.
 * When a mod stage is being loaded, this module checks the catalog's
 * component directory for the requested file before the legacy mod system.
 *
 * Architecture:
 *   - Completely standalone: does not modify g_Stages[], modmgr, or any
 *     legacy data structures.
 *   - Stage context: lvReset() calls assetCatalogActivateStage() to set
 *     which catalog component (if any) should resolve files.
 *   - File resolution: fsFullPath() calls assetCatalogResolvePath() as a
 *     priority check before modmgrResolvePath().
 *   - Falls through silently if no catalog component applies.
 *
 * This module coexists with the legacy mod system. Both can resolve files;
 * the catalog gets first priority. Over time (D3R-11), the legacy system
 * is removed and the catalog becomes the sole resolver.
 */

#ifndef _IN_ASSETCATALOG_RESOLVE_H
#define _IN_ASSETCATALOG_RESOLVE_H

#include <PR/ultratypes.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Find a non-bundled ASSET_MAP entry by stagenum.
 * Scans all enabled map entries for one matching the given stagenum.
 * Returns const pointer to the entry, or NULL if no mod component found.
 * Base game stages (bundled=1) are excluded -- they use the legacy path.
 */
const struct asset_entry *assetCatalogFindModMapByStagenum(s32 stagenum);

/**
 * Set the active catalog stage for file resolution.
 * If a non-bundled catalog component exists for this stagenum, file
 * requests will check its directory first.
 * Call at the start of stage loading (e.g., in lvReset()).
 * Pass -1 or a base-game stagenum to deactivate.
 */
void assetCatalogActivateStage(s32 stagenum);

/**
 * Clear the active stage context.
 * Call when stage loading is complete or when returning to menus.
 */
void assetCatalogDeactivateStage(void);

/**
 * Resolve a relative file path through the active catalog component.
 * If a mod component is active for the current stage, checks its directory
 * for the requested file. Returns full path if found, NULL otherwise.
 *
 * The returned pointer is to a static buffer -- valid until the next call.
 * Thread safety: single-threaded only (same as the rest of the catalog).
 *
 * @param relPath  Relative path as generated by romdata (e.g., "files/bgdata/bg_arec.seg")
 * @return         Full path to file in component directory, or NULL
 */
const char *assetCatalogResolvePath(const char *relPath);

#ifdef __cplusplus
}
#endif

#endif /* _IN_ASSETCATALOG_RESOLVE_H */
