#ifndef PD_LOADER_PDBASE_ENUMS_H
#define PD_LOADER_PDBASE_ENUMS_H

#include <PR/ultratypes.h>

/*
 * port/include/loader_pdbase_enums.h -- S484 F12: enum lookup tables for the
 * .pdbase loader.
 *
 * The .pdbase JSON archive uses STRINGS for symbolic enum references
 * (ANIM_*, SFX_*, FILE_*, L_GUN_*) so the data is human-readable and
 * mod-authorable. The loader resolves these strings to integer values
 * via the tables in port/src/loader_pdbase_enums.c (generated by
 * devtools/extract_weapons_pdbase.py from the relevant headers).
 *
 * Design rationale:
 *   - JSON readability vs runtime cost trade-off: name lookup is a
 *     one-time per-load operation. Lookup tables are linear-scan
 *     because the .pdbase load happens once at startup; switching to
 *     bsearch is a profile-driven future optimization.
 *   - Enum resolution stays at the loader boundary so the manager and
 *     gameplay code only ever see integer values.
 *   - Each resolver takes a `fallback` so the loader can decide
 *     per-call whether a missing name is a hard error or soft default
 *     (zero is currently used as the implicit default; per-element
 *     failure granularity drops the field rather than aborting the
 *     whole load).
 *
 * Future work:
 *   - When mod authoring needs to add new enum values (e.g. a mod
 *     defines its own animation or sound), the resolver path will
 *     extend to consult per-mod overlay tables in addition to the
 *     base-game tables generated here.
 */

#ifdef __cplusplus
extern "C" {
#endif

s32 loaderPdbaseResolveAnimEnum(const char *name, s32 fallback);
s32 loaderPdbaseResolveSfxEnum(const char *name, s32 fallback);
s32 loaderPdbaseResolveLangEnum(const char *name, s32 fallback);
s32 loaderPdbaseResolveFileEnum(const char *name, s32 fallback);

/* Catalog universality pivot Step 1: reverse lookup (value -> name).
 * Returns NULL if no match. Linear scan; emit-time use only. */
const char *loaderPdbaseNameForAnimEnum(s32 value);
const char *loaderPdbaseNameForSfxEnum(s32 value);
const char *loaderPdbaseNameForLangEnum(s32 value);
const char *loaderPdbaseNameForFileEnum(s32 value);

#ifdef __cplusplus
}
#endif

#endif /* PD_LOADER_PDBASE_ENUMS_H */
