/**
 * updater_pubkey.h -- Embedded Ed25519 public key for the signed updater (SEC-6).
 *
 * This public key is the root of trust for auto-updates. Every release ZIP
 * downloaded by updater.c must carry a .sig sidecar that is a valid Ed25519
 * signature over the ZIP's SHA-256 digest concatenated with the tag string
 * (e.g. "v0.0.21"), signed by the matching private key. If the signature
 * does not verify, the update is rejected before any files are staged.
 *
 * Trust properties:
 *   - The public key does NOT rotate with the distribution channel (GitHub
 *     Releases). Compromising the GitHub account cannot forge a valid
 *     signature — only compromise of the private key can.
 *   - SHA-256 verification is independent (SEC-5). This binds the signature
 *     to the exact bytes of the ZIP.
 *   - The tag string is part of the signed message, so an attacker cannot
 *     re-use a signature from an older release on a different version tag.
 *
 * Key management:
 *   - DEVELOPMENT KEY: The constants below are a development key generated by
 *     devtools/keygen.ps1 (or keygen.sh). The matching private key lives in
 *     dev-keys/ed25519-private.pem and is gitignored.
 *   - PRODUCTION KEY: Before shipping a stable release to the general public,
 *     the developer MUST generate a separate production keypair offline and
 *     replace the constants below. The production private key MUST NEVER be
 *     checked into git, stored on a build server, or shared over any
 *     network — loss of that key permanently compromises the update channel.
 *
 * Regeneration:
 *   devtools/keygen.ps1       # Windows: writes updated public key into this file
 *   devtools/keygen.sh        # bash: same, for Linux/macOS dev machines
 */

#ifndef _IN_UPDATER_PUBKEY_H
#define _IN_UPDATER_PUBKEY_H

#include <PR/ultratypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#define UPDATER_PUBKEY_SIZE 32

/* BEGIN UPDATER_PUBKEY (do not edit by hand — regenerate via devtools/keygen) */
/* Type: DEVELOPMENT (not for production release) */
/* Generated: 2026-04-19 */
static const u8 UPDATER_PUBKEY[UPDATER_PUBKEY_SIZE] = {
	0x8d, 0xe2, 0xd8, 0x5b, 0x07, 0xf7, 0xb0, 0x19,
	0xc8, 0x82, 0xd2, 0x5a, 0x3a, 0x85, 0x31, 0x73,
	0xcd, 0xeb, 0x83, 0x01, 0x0b, 0x7e, 0xd2, 0x20,
	0x01, 0x5b, 0x81, 0x6b, 0x60, 0xf8, 0xdc, 0x12,
};
/* END UPDATER_PUBKEY */

#ifdef __cplusplus
}
#endif

#endif /* _IN_UPDATER_PUBKEY_H */
