/**
 * updater_pubkey.h -- Embedded Ed25519 public key for the signed updater (SEC-6).
 *
 * This public key is the root of trust for auto-updates. Every release ZIP
 * downloaded by updater.c must carry a .sig sidecar that is a valid Ed25519
 * signature over the ZIP's SHA-256 digest concatenated with the tag string
 * (e.g. "v0.0.21"), signed by the matching private key. If the signature
 * does not verify, the update is rejected before any files are staged.
 *
 * Trust properties:
 *   - The public key does NOT rotate with the distribution channel (GitHub
 *     Releases). Compromising the GitHub account cannot forge a valid
 *     signature â€” only compromise of the private key can.
 *   - SHA-256 verification is independent (SEC-5). This binds the signature
 *     to the exact bytes of the ZIP.
 *   - The tag string is part of the signed message, so an attacker cannot
 *     re-use a signature from an older release on a different version tag.
 *
 * Key management:
 *   The constants below are generated by devtools/keygen.ps1. The matching
 *   private key lives in dev-keys/ed25519-private.pem and is gitignored.
 *   The keypair is generated automatically on the first build if missing
 *   (build-env.sh / build-headless.ps1 both call keygen.ps1). To rotate
 *   the key, run: .\devtools\keygen.ps1 -Force (then rebuild all clients).
 *
 * Regeneration:
 *   .\devtools\keygen.ps1 -Force   # rotate key, patches this file
 */

#ifndef _IN_UPDATER_PUBKEY_H
#define _IN_UPDATER_PUBKEY_H

#include <PR/ultratypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#define UPDATER_PUBKEY_SIZE 32

/* BEGIN UPDATER_PUBKEY (do not edit by hand -- regenerate via devtools/keygen) */
/* Type: DEVELOPMENT */
/* Generated: 2026-05-03 */
static const u8 UPDATER_PUBKEY[UPDATER_PUBKEY_SIZE] = {
	0x3e, 0x26, 0xc3, 0xd0, 0x3b, 0xa5, 0x75, 0xdb,
	0x25, 0x53, 0xf5, 0xb7, 0xf3, 0x7f, 0xc8, 0x9c,
	0x87, 0x98, 0x96, 0xa5, 0x5e, 0xf8, 0x61, 0x8b,
	0xc1, 0x3b, 0xa6, 0x21, 0x7d, 0x83, 0xee, 0xf1,
};
/* END UPDATER_PUBKEY */

#ifdef __cplusplus
}
#endif

#endif /* _IN_UPDATER_PUBKEY_H */
