/**
 * updater_pubkey.h -- Embedded Ed25519 public key for the signed updater (SEC-6).
 *
 * This public key is the root of trust for auto-updates. Every release ZIP
 * downloaded by updater.c must carry a .sig sidecar that is a valid Ed25519
 * signature over the ZIP's SHA-256 digest concatenated with the tag string
 * (e.g. "v0.0.21"), signed by the matching private key. If the signature
 * does not verify, the update is rejected before any files are staged.
 *
 * Trust properties:
 *   - The public key does NOT rotate with the distribution channel (GitHub
 *     Releases). Compromising the GitHub account cannot forge a valid
 *     signature â€” only compromise of the private key can.
 *   - SHA-256 verification is independent (SEC-5). This binds the signature
 *     to the exact bytes of the ZIP.
 *   - The tag string is part of the signed message, so an attacker cannot
 *     re-use a signature from an older release on a different version tag.
 *
 * Key management:
 *   The constants below are generated by devtools/keygen.ps1. The matching
 *   private key lives in dev-keys/ed25519-private.pem and is gitignored.
 *   The keypair is generated automatically on the first build if missing
 *   (build-env.sh / build-headless.ps1 both call keygen.ps1). To rotate
 *   the key, run: .\devtools\keygen.ps1 -Force (then rebuild all clients).
 *
 * Regeneration:
 *   .\devtools\keygen.ps1 -Force   # rotate key, patches this file
 */

#ifndef _IN_UPDATER_PUBKEY_H
#define _IN_UPDATER_PUBKEY_H

#include <PR/ultratypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#define UPDATER_PUBKEY_SIZE 32

/* BEGIN UPDATER_PUBKEY (do not edit by hand -- regenerate via devtools/keygen) */
/* Type: DEVELOPMENT */
/* Generated: 2026-04-19 */
static const u8 UPDATER_PUBKEY[UPDATER_PUBKEY_SIZE] = {
	0xb7, 0x57, 0x2e, 0xdf, 0xe8, 0xbb, 0x0c, 0xa4,
	0x38, 0x39, 0xa4, 0x16, 0x88, 0xee, 0x1a, 0x75,
	0x64, 0xb8, 0x7c, 0x05, 0xd8, 0xca, 0xed, 0x04,
	0x6e, 0x53, 0xf4, 0x30, 0x30, 0x67, 0x55, 0xac,
};
/* END UPDATER_PUBKEY */

#ifdef __cplusplus
}
#endif

#endif /* _IN_UPDATER_PUBKEY_H */
