<#
.SYNOPSIS
  Install Perfect Dark 2 git hooks and self-test the commit-msg validator.

.DESCRIPTION
  Configures git to use .githooks/ as the hooks directory and verifies the
  commit-msg hook rejects bad messages and accepts well-formed ones.

  Idempotent. Safe to run multiple times. Local config, so one install
  covers every worktree of this repo.

  Bypass during emergencies: git commit --no-verify (only with explicit
  authorization).

.PARAMETER SkipSelfTest
  Configure core.hooksPath without running the rejection / acceptance probe.
  Used by CI or automated callers that just want the configuration step.

.EXAMPLE
  pwsh tools/install-githooks.ps1

.EXAMPLE
  pwsh tools/install-githooks.ps1 -SkipSelfTest
#>

[CmdletBinding()]
param(
  [switch]$SkipSelfTest
)

$ErrorActionPreference = 'Stop'

function Get-RepoRoot {
  $top = (& git rev-parse --show-toplevel) 2>$null
  if ($LASTEXITCODE -ne 0 -or -not $top) {
    throw 'Not inside a git repository (git rev-parse --show-toplevel failed).'
  }
  return ($top.Trim() -replace '/', '\')
}

function Resolve-Python {
  foreach ($candidate in @('python3', 'python', 'py')) {
    $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
  }
  throw 'No python interpreter found on PATH (tried python3, python, py).'
}

function Test-CommitMsgRejection {
  param(
    [Parameter(Mandatory)] [string]$RepoRoot,
    [Parameter(Mandatory)] [string]$PythonExe,
    [Parameter(Mandatory)] [string]$BadMessage
  )

  $tmpFile = New-TemporaryFile
  try {
    Set-Content -Path $tmpFile.FullName -Value $BadMessage -Encoding utf8
    Push-Location $RepoRoot
    try {
      $hookScript = Join-Path $RepoRoot '.githooks\commit-msg.py'
      & $PythonExe $hookScript $tmpFile.FullName 2>&1 | Out-Null
      return $LASTEXITCODE
    } finally {
      Pop-Location
    }
  } finally {
    Remove-Item -Force $tmpFile.FullName -ErrorAction SilentlyContinue
  }
}

# Main.

$repoRoot = Get-RepoRoot
Set-Location $repoRoot

$hookDir = Join-Path $repoRoot '.githooks'
$hookSh  = Join-Path $hookDir 'commit-msg'
$hookPy  = Join-Path $hookDir 'commit-msg.py'

if (-not (Test-Path $hookDir)) {
  throw "Missing .githooks directory at $hookDir. Check out a revision that contains the hook."
}
if (-not (Test-Path $hookSh)) {
  throw "Missing $hookSh."
}
if (-not (Test-Path $hookPy)) {
  throw "Missing $hookPy."
}

# Verify python is available, since the hook needs it.
$pythonExe = Resolve-Python
Write-Host "Using python: $pythonExe"

# Configure core.hooksPath idempotently.
$currentPath = (& git config --get core.hooksPath) 2>$null
$desiredPath = '.githooks'
if ($currentPath -ne $desiredPath) {
  Write-Host "Setting git config core.hooksPath = $desiredPath (was: $currentPath)"
  & git config core.hooksPath $desiredPath
  if ($LASTEXITCODE -ne 0) {
    throw 'Failed to set core.hooksPath.'
  }
} else {
  Write-Host 'core.hooksPath already configured.'
}

# Mark the shell entry executable. On Windows the bit is stored in the git
# index but is otherwise a no-op for the filesystem; the hook runs regardless
# under Git for Windows MSYS bash.
& git update-index --chmod=+x -- .githooks/commit-msg 2>$null | Out-Null
& git update-index --chmod=+x -- .githooks/commit-msg.py 2>$null | Out-Null

if ($SkipSelfTest) {
  Write-Host 'SkipSelfTest set. Install complete.'
  return
}

Write-Host ''
Write-Host 'Self-test: probing the validator directly (no real commits made).'

# 1. Bad message should exit non-zero.
$badMsg = 'wip'
$badCode = Test-CommitMsgRejection -RepoRoot $repoRoot -PythonExe $pythonExe -BadMessage $badMsg
if ($badCode -eq 0) {
  throw "Self-test FAILED: validator accepted a bare 'wip' message (exit 0)."
}
Write-Host "  [PASS] rejected 'wip' (exit $badCode)"

# 2. Bad subject format should exit non-zero.
$badFmt = 'chore: random update'
$fmtCode = Test-CommitMsgRejection -RepoRoot $repoRoot -PythonExe $pythonExe -BadMessage $badFmt
if ($fmtCode -eq 0) {
  throw "Self-test FAILED: validator accepted 'chore: random update' (exit 0)."
}
Write-Host "  [PASS] rejected 'chore: random update' (exit $fmtCode)"

# 3. Subject ok but missing Refs trailer should exit non-zero.
$missingRefs = @"
Tooling - c120: Self-test missing refs trailer

This message has a valid subject and a body paragraph, but no Refs trailer,
so the validator must reject it.
"@
$refsCode = Test-CommitMsgRejection -RepoRoot $repoRoot -PythonExe $pythonExe -BadMessage $missingRefs
if ($refsCode -eq 0) {
  throw 'Self-test FAILED: validator accepted a message with no Refs trailer.'
}
Write-Host "  [PASS] rejected missing-Refs message (exit $refsCode)"

# 4. Well-formed message should exit zero.
$goodMsg = @"
Tooling - c120: Self-test commit-msg acceptance probe

This is a synthetic message generated by tools/install-githooks.ps1 during
the self-test. It demonstrates the required format: subject prefix, body
paragraph, and Refs trailer.

Refs: c120
"@
$okCode = Test-CommitMsgRejection -RepoRoot $repoRoot -PythonExe $pythonExe -BadMessage $goodMsg
if ($okCode -ne 0) {
  throw "Self-test FAILED: validator rejected a well-formed message (exit $okCode)."
}
Write-Host "  [PASS] accepted well-formed message (exit 0)"

Write-Host ''
Write-Host 'Self-test passed. commit-msg hook is active for this repo.'
Write-Host 'Format reminder:  <Pillar> - <CardID>: <summary>'
Write-Host 'Reference:        context/designs/commit-message-standard.md'
